bestdevhyo1225/large-system-design

shortened-url-server/build.gradle.kts
shortened-url-server/requests.http
shortened-url-server/src/main/kotlin/com/hyoseok/ShortenedUrlServerApplication.kt
shortened-url-server/src/main/kotlin/com/hyoseok/common/constants/ServerExceptionMessage.kt
shortened-url-server/src/main/kotlin/com/hyoseok/common/utils/Base62Util.kt
shortened-url-server/src/main/kotlin/com/hyoseok/domain/entity/Url.kt
shortened-url-server/src/main/kotlin/com/hyoseok/domain/repository/UrlRepository.kt
shortened-url-server/src/main/kotlin/com/hyoseok/exception/GlobalExceptionHandler.kt
shortened-url-server/src/main/kotlin/com/hyoseok/service/UrlService.kt
shortened-url-server/src/main/kotlin/com/hyoseok/web/UrlController.kt
shortened-url-server/src/main/kotlin/com/hyoseok/web/request/CreateUrlRequest.kt
shortened-url-server/src/main/kotlin/com/hyoseok/web/response/ErrorResponse.kt
shortened-url-server/src/main/kotlin/com/hyoseok/web/response/FailResponse.kt
shortened-url-server/src/main/kotlin/com/hyoseok/web/response/SuccessResponse.kt
shortened-url-server/src/main/resources/application.yml
shortened-url-server/src/test/kotlin/com/hyoseok/common/utils/Base62UtilTests.kt
shortened-url-server/src/test/kotlin/com/hyoseok/domain/entity/UrlTests.kt
shortened-url-server/src/test/resources/applitcation.yml

[PR] URL 단축 서버 개발

---

shortened-url-server/src/main/kotlin/com/hyoseok/common/utils/Base62Util.kt

- StringBuilder의 `append()` 제거
- StringBuilder의 `insert(0, value)` 함수로 대체
- `reverse()` 를 제거한 결과를 반환

[PR] StringBuilder의 결과에서 reverse() 제거해서 반환

---

docker/mysql/replication/clean.sh
docker/mysql/replication/docker-compose.yml
docker/mysql/replication/init.sh
docker/mysql/replication/mysql.Dockerfile
docker/mysql/replication/read.sh
docker/mysql/replication/read/mysql-config-files/my.cnf
docker/mysql/replication/read/mysql-init-files/init.sql
docker/mysql/replication/write.sh
docker/mysql/replication/write/mysql-config-files/my.cnf
docker/mysql/replication/write/mysql-init-files/init.sql
shortened-url-server/requests.http
shortened-url-server/src/main/kotlin/com/hyoseok/config/mysql/replication/ReplicationDataSourceConfig.kt
shortened-url-server/src/main/kotlin/com/hyoseok/config/mysql/replication/ReplicationDataSourceType.kt
shortened-url-server/src/main/kotlin/com/hyoseok/config/mysql/replication/ReplicationRoutingDataSource.kt
shortened-url-server/src/main/kotlin/com/hyoseok/config/mysql/replication/property/ReadProperty.kt
shortened-url-server/src/main/kotlin/com/hyoseok/config/mysql/replication/property/WriteProperty.kt
shortened-url-server/src/main/resources/application.yml

- #2
- Docker MySQL Replication 구축
- MySQL Replication DataSource 설정

[PR] MySQL Replication DataSource 설정

---

shortened-url-server/Dockerfile
shortened-url-server/build.gradle.kts
shortened-url-server/docker-compose.yml
shortened-url-server/src/main/kotlin/com/hyoseok/config/mysql/replication/ReplicationDataSourceConfig.kt
shortened-url-server/src/main/kotlin/com/hyoseok/config/mysql/replication/property/ReadProperty.kt
shortened-url-server/src/main/kotlin/com/hyoseok/config/mysql/replication/property/WriteProperty.kt
shortened-url-server/src/main/resources/application.yml
shortened-url-server/start.sh
shortened-url-server/stop.sh

- #2
- `./gradlew` 명령어로 `.jar` 파일을 실행할 수 있도록 `org.springframework.boot` 플러그인 활성화
- 없으면, `기본 manifest 속성이 없습니다.` 에러가 발생함.
- Docker Image 및 Docker Container 구축
- Docker Container 시작 및 종료  쉘 스크립트 추가

[PR] URL 단축 서버에 대한 Docker 관련 작업

---

shortened-url-server/src/main/kotlin/com/hyoseok/web/UrlController.kt

[PR] 301 응답 임시 주석처리

---

README.md
docker/mysql/replication/docker-compose.yml
shortened-url-server/docker-compose.yml

[PR] MySQL 부하 테스트 결과 작성

---

README.md
build.gradle.kts
docker/redis/docker-compose.yml
shortened-url-server/build.gradle.kts
shortened-url-server/src/main/kotlin/com/hyoseok/config/redis/RedisExpireTimes.kt
shortened-url-server/src/main/kotlin/com/hyoseok/config/redis/RedisKeys.kt
shortened-url-server/src/main/kotlin/com/hyoseok/config/redis/RedisStandaloneConfig.kt
shortened-url-server/src/main/kotlin/com/hyoseok/config/redis/RedisTemplateConfig.kt
shortened-url-server/src/main/kotlin/com/hyoseok/domain/repository/UrlCacheRepository.kt
shortened-url-server/src/main/kotlin/com/hyoseok/infrastructure/redis/UrlRedisRepository.kt
shortened-url-server/src/main/kotlin/com/hyoseok/service/UrlFacadeService.kt
shortened-url-server/src/main/kotlin/com/hyoseok/service/UrlService.kt
shortened-url-server/src/main/kotlin/com/hyoseok/web/UrlController.kt
shortened-url-server/src/main/resources/application.yml

- #2 
- `Docker Redis` 정의
- `kotlinx-coroutines-core`, `spring-data-redis` 의존성 모듈 추가
- `Redis` Connection, Keys, ExpireTimes, Template 클래스 구현
- `longUrl` 조회에 대한 캐시 저장 및 조회 기능 구현

[PR] Redis 구축 및 캐시 저장, 조회 기능 개발

---

shortened-url-server/src/main/kotlin/com/hyoseok/config/redis/RedisStandaloneConfig.kt
shortened-url-server/src/main/resources/application.yml

[PR] command-timeout 옵션 제거, 디폴트 값 사용

---

settings.gradle.kts
shortened-url-server-ver3/domain/src/main/kotlin/com/hyoseok/repository/UrlCacheRepository.kt
shortened-url-server-ver3/infrastructure/redis/build.gradle.kts
shortened-url-server-ver3/infrastructure/redis/src/main/kotlin/com/hyoseok/config/RedisExpireTimes.kt
shortened-url-server-ver3/infrastructure/redis/src/main/kotlin/com/hyoseok/config/RedisKeys.kt
shortened-url-server-ver3/infrastructure/redis/src/main/kotlin/com/hyoseok/config/RedisNodesKey.kt
shortened-url-server-ver3/infrastructure/redis/src/main/kotlin/com/hyoseok/config/standalone/multiple/RedisMultipleStandaloneConfig.kt
shortened-url-server-ver3/infrastructure/redis/src/main/kotlin/com/hyoseok/config/standalone/multiple/RedisMultipleStandaloneTemplateConfig.kt
shortened-url-server-ver3/infrastructure/redis/src/main/kotlin/com/hyoseok/config/standalone/multiple/property/RedisServers.kt
shortened-url-server-ver3/infrastructure/redis/src/main/kotlin/com/hyoseok/repository/AbstractRedisRepository.kt
shortened-url-server-ver3/infrastructure/redis/src/main/kotlin/com/hyoseok/repository/UrlMultipleRedisRepository1.kt
shortened-url-server-ver3/infrastructure/redis/src/main/kotlin/com/hyoseok/repository/UrlMultipleRedisRepository2.kt
shortened-url-server-ver3/infrastructure/redis/src/main/kotlin/com/hyoseok/repository/UrlMultipleRedisRepository3.kt
shortened-url-server-ver3/infrastructure/redis/src/main/kotlin/com/hyoseok/repository/UrlRedisRepository.kt
shortened-url-server-ver3/query/build.gradle.kts
shortened-url-server-ver3/query/requests.http
shortened-url-server-ver3/query/src/main/kotlin/com/hyoseok/QueryVer2Application.kt
shortened-url-server-ver3/query/src/main/kotlin/com/hyoseok/exception/GlobalExceptionHandler.kt
shortened-url-server-ver3/query/src/main/kotlin/com/hyoseok/service/UrlFacadeService.kt
shortened-url-server-ver3/query/src/main/kotlin/com/hyoseok/web/UrlController.kt
shortened-url-server-ver3/query/src/main/kotlin/com/hyoseok/web/response/ErrorResponse.kt
shortened-url-server-ver3/query/src/main/kotlin/com/hyoseok/web/response/FailResponse.kt
shortened-url-server-ver3/query/src/main/kotlin/com/hyoseok/web/response/SuccessResponse.kt
shortened-url-server-ver3/query/src/main/resources/application.yml

[PR] Redis Standalone 서버 3대 구축

---

order-payment-server/domain/src/main/kotlin/com/bestdev/order/repository/OrderRepository.kt
order-payment-server/infrastructure/jpa/src/main/kotlin/com/bestdev/entity/order/OrderJpaEntity.kt
order-payment-server/infrastructure/jpa/src/main/kotlin/com/bestdev/repository/order/OrderRepositoryAdapter.kt
order-payment-server/infrastructure/jpa/src/test/kotlin/com/bestdev/order/repository/OrderRepositoryAdapterTests.kt

- JPA 변경 감지 기능에 의한 Update 쿼리 실행 되도록 기능 추가

[PR] JPA 변경 감지 기능에 의해서 주문 상태를 변경하는 기능 구현

---

.editorconfig
order-payment-server/api/requests.http
order-payment-server/api/src/main/kotlin/com/bestdev/exception/GlobalExceptionHandler.kt
order-payment-server/api/src/main/kotlin/com/bestdev/service/OrderService.kt
order-payment-server/api/src/main/kotlin/com/bestdev/service/dto/CreateOrderDto.kt
order-payment-server/api/src/main/kotlin/com/bestdev/web/OrderController.kt
order-payment-server/api/src/main/kotlin/com/bestdev/web/request/CreateOrderRequest.kt
order-payment-server/api/src/main/kotlin/com/bestdev/web/response/ErrorResponse.kt
order-payment-server/api/src/main/kotlin/com/bestdev/web/response/FailResponse.kt
order-payment-server/api/src/main/kotlin/com/bestdev/web/response/SuccessResponse.kt
order-payment-server/api/src/main/resources/application.yml
order-payment-server/domain/src/main/kotlin/com/bestdev/order/entity/Order.kt
order-payment-server/domain/src/main/kotlin/com/bestdev/order/entity/enums/OrderStatus.kt
order-payment-server/domain/src/test/kotlin/com/bestdev/order/OrderTests.kt
order-payment-server/infrastructure/jpa/src/main/kotlin/com/bestdev/entity/order/OrderJpaEntity.kt
order-payment-server/infrastructure/jpa/src/main/kotlin/com/bestdev/repository/order/OrderJpaRepository.kt
order-payment-server/infrastructure/jpa/src/main/kotlin/com/bestdev/repository/order/OrderRepositoryAdapter.kt
order-payment-server/infrastructure/jpa/src/test/kotlin/com/bestdev/order/repository/OrderRepositoryAdapterTests.kt

- Domain 모듈 수정
- Infrastructure 모듈 수정
- Api 모듈에 주문 생성, 주문 상태 변경 기능 구현

[PR] 주문 생성 및 상태 변경 기능 개발

---

order-payment-server/domain/src/main/kotlin/com/bestdev/payment/entity/Payment.kt
order-payment-server/domain/src/main/kotlin/com/bestdev/payment/repository/PaymentRepository.kt
order-payment-server/infrastructure/jpa/src/main/kotlin/com/bestdev/entity/payment/PaymentJpaEntity.kt
order-payment-server/infrastructure/jpa/src/main/kotlin/com/bestdev/exception/InfrastructureExceptionMessage.kt
order-payment-server/infrastructure/jpa/src/main/kotlin/com/bestdev/repository/order/OrderJpaRepositoryAdapter.kt
order-payment-server/infrastructure/jpa/src/main/kotlin/com/bestdev/repository/payment/PaymentJpaRepository.kt
order-payment-server/infrastructure/jpa/src/main/kotlin/com/bestdev/repository/payment/PaymentJpaRepositoryAdapter.kt
order-payment-server/infrastructure/jpa/src/test/kotlin/com/bestdev/order/repository/OrderJpaRepositoryAdapterTestable.kt
order-payment-server/infrastructure/jpa/src/test/kotlin/com/bestdev/order/repository/OrderJpaRepositoryAdapterTests.kt
order-payment-server/infrastructure/jpa/src/test/kotlin/com/bestdev/payment/repository/PaymentJpaRepositoryAdapterTestable.kt
order-payment-server/infrastructure/jpa/src/test/kotlin/com/bestdev/payment/repository/PaymentJpaRepositoryAdapterTests.kt

- Domain 모듈
- Infrastructure/Jpa 모듈

[PR] PaymentJpaRepository 구현

---

order-payment-server/api/src/main/kotlin/com/bestdev/service/dto/CreateOrderDto.kt
order-payment-server/api/src/main/kotlin/com/bestdev/web/request/CreateOrderRequest.kt
order-payment-server/domain/src/main/kotlin/com/bestdev/order/entity/Order.kt
order-payment-server/domain/src/main/kotlin/com/bestdev/order/entity/OrderItem.kt
order-payment-server/domain/src/main/kotlin/com/bestdev/order/entity/OrderPayment.kt
order-payment-server/domain/src/main/kotlin/com/bestdev/order/entity/enums/OrderItemCategory.kt
order-payment-server/domain/src/main/kotlin/com/bestdev/order/entity/enums/OrderPaymentMethod.kt
order-payment-server/domain/src/test/kotlin/com/bestdev/order/OrderTests.kt
order-payment-server/infrastructure/jpa/src/main/kotlin/com/bestdev/entity/order/OrderItemJpaEntity.kt
order-payment-server/infrastructure/jpa/src/main/kotlin/com/bestdev/entity/order/OrderJpaEntity.kt
order-payment-server/infrastructure/jpa/src/main/kotlin/com/bestdev/entity/order/OrderPaymentJpaEntity.kt
order-payment-server/infrastructure/jpa/src/test/kotlin/com/bestdev/order/repository/OrderJpaRepositoryAdapterTests.kt

- `api` 모듈 개발
- `infrastructure:jpa`  모듈 개발

[PR] Order, OrderItem, OrderPayment 엔티티가 한 사이클에서 저장되도록 기능 리팩토링

---

settings.gradle.kts
shortened-url-server-ver3/command/build.gradle.kts
shortened-url-server-ver3/command/src/main/kotlin/com/hyoseok/service/UrlService.kt
shortened-url-server-ver3/command/src/main/resources/application.yml
shortened-url-server-ver3/domain/src/main/kotlin/com/hyoseok/repository/UrlRepository.kt
shortened-url-server-ver3/infrastructure/jpa/src/main/kotlin/com/hyoseok/repository/UrlJpaRepositoryAdapter.kt
shortened-url-server-ver3/infrastructure/resilience4j/build.gradle.kts
shortened-url-server-ver3/infrastructure/resilience4j/src/main/kotlin/com/hyoseok/config/Resilience4jConfig.kt
shortened-url-server-ver3/query/build.gradle.kts
shortened-url-server-ver3/query/src/main/kotlin/com/hyoseok/service/UrlFacadeService.kt
shortened-url-server-ver3/query/src/main/kotlin/com/hyoseok/service/UrlService.kt
shortened-url-server-ver3/query/src/main/resources/application.yml

- `command` 모듈 개발
- `infrastructure:resilience4j` 모듈 개발
- `query` 모듈 개발

[PR] resilience4j 라이브러리를 활용한 Circuit Breaker 구축

---

shortened-url-server-ver3/common/src/main/kotlin/com/hyoseok/constants/CircuitBreakerName.kt
shortened-url-server-ver3/infrastructure/jpa/src/main/kotlin/com/hyoseok/config/resilience4j/Resilience4jConfig.kt
shortened-url-server-ver3/infrastructure/jpa/src/main/kotlin/com/hyoseok/repository/UrlJpaRepositoryAdapter.kt
shortened-url-server-ver3/infrastructure/redis/build.gradle.kts
shortened-url-server-ver3/infrastructure/redis/src/main/kotlin/com/hyoseok/config/resilience4j/Resilience4jConfig.kt
shortened-url-server-ver3/infrastructure/redis/src/main/kotlin/com/hyoseok/repository/UrlRedisRepository.kt

[PR] Redis 서킷 브레이커 적용

---

shortened-url-server-ver3/infrastructure/r2dbc/src/main/kotlin/com/hyoseok/config/mysql/replication/ReplicationConnectionConfig.kt

- #33
- `infrastructure:r2dbc` 모듈 리팩토링

[PR] R2DBC 설정 리팩토링

---

shortened-url-server-ver3/infrastructure/r2dbc/build.gradle.kts
shortened-url-server-ver3/infrastructure/r2dbc/src/test/kotlin/com/hyoseok/repository/UrlNonBlockingRepositoryAdapterTests.kt
shortened-url-server-ver3/infrastructure/r2dbc/src/test/resources/application.yml

[PR] RepositoryAdapter 클래스에 대한 단위 테스트 추가

---

settings.gradle.kts
sns-service/common/src/main/kotlin/com/hyoseok/constants/CircuitBreakerName.kt
sns-service/common/src/main/kotlin/com/hyoseok/utils/Base62Util.kt
sns-service/common/src/main/kotlin/com/hyoseok/utils/Crc32Util.kt
sns-service/common/src/main/kotlin/com/hyoseok/utils/Sha256Util.kt
sns-service/domain/build.gradle.kts
sns-service/infrastructure/aws/build.gradle.kts

[PR] common, infrastructure:aws 모듈 추가

---

sns-service/data/jpa/build.gradle.kts
sns-service/data/jpa/src/main/kotlin/com/hyoseok/config/jpa/JpaConfig.kt
sns-service/data/jpa/src/main/kotlin/com/hyoseok/config/jpa/JpaQueryFactoryConfig.kt
sns-service/data/jpa/src/main/kotlin/com/hyoseok/config/mysql/BasicDataSourceConfig.kt
sns-service/data/jpa/src/main/kotlin/com/hyoseok/config/mysql/replication/ReplicationDataSourceConfig.kt
sns-service/data/jpa/src/main/kotlin/com/hyoseok/config/mysql/replication/ReplicationDataSourceType.kt
sns-service/data/jpa/src/main/kotlin/com/hyoseok/config/mysql/replication/ReplicationRoutingDataSource.kt
sns-service/data/jpa/src/main/kotlin/com/hyoseok/config/mysql/replication/property/ReadProperty.kt
sns-service/data/jpa/src/main/kotlin/com/hyoseok/config/mysql/replication/property/WriteProperty.kt
sns-service/data/jpa/src/main/kotlin/com/hyoseok/entity/sns/SnsImageJpaEntity.kt
sns-service/data/jpa/src/main/kotlin/com/hyoseok/entity/sns/SnsJpaEntity.kt
sns-service/data/jpa/src/main/kotlin/com/hyoseok/entity/sns/SnsTagJpaEntity.kt
sns-service/data/jpa/src/main/kotlin/com/hyoseok/exception/Message.kt
sns-service/data/jpa/src/main/kotlin/com/hyoseok/repository/sns/SnsJpaRepository.kt
sns-service/data/jpa/src/main/kotlin/com/hyoseok/repository/sns/SnsRepositoryImpl.kt
sns-service/data/jpa/src/main/kotlin/com/hyoseok/repository/sns/read/SnsReadRepositoryImpl.kt
sns-service/data/jpa/src/test/kotlin/com/hyoseok/repository/RepositoryImplTests.kt
sns-service/data/jpa/src/test/kotlin/com/hyoseok/repository/sns/SnsRepositoryImplTests.kt
sns-service/data/jpa/src/test/resources/application.yml
sns-service/domain/src/main/kotlin/com/hyoseok/sns/entity/Sns.kt
sns-service/domain/src/main/kotlin/com/hyoseok/sns/entity/SnsImage.kt
sns-service/domain/src/main/kotlin/com/hyoseok/sns/repository/read/SnsReadRepository.kt
sns-service/domain/src/test/kotlin/com/hyoseok/sns/entity/SnsTests.kt

- #39
- `url` 프로퍼티에 `sha-256` 해시 알고리즘 적용

[PR] SNS 엔티티 수정, JPA 모듈 개발

---

sns-service/application/command/requests.http
sns-service/application/command/src/main/kotlin/com/hyoseok/service/SnsService.kt
sns-service/application/command/src/main/kotlin/com/hyoseok/service/dto/ProductDto.kt
sns-service/application/command/src/main/kotlin/com/hyoseok/service/dto/SnsDto.kt
sns-service/application/command/src/main/kotlin/com/hyoseok/web/request/ProductRequest.kt
sns-service/application/command/src/main/kotlin/com/hyoseok/web/request/SnsRequest.kt
sns-service/data/jpa/src/main/kotlin/com/hyoseok/entity/product/ExternalProductJpaEntity.kt
sns-service/data/jpa/src/main/kotlin/com/hyoseok/entity/sns/SnsJpaEntity.kt
sns-service/data/jpa/src/main/kotlin/com/hyoseok/exception/Message.kt
sns-service/data/jpa/src/main/kotlin/com/hyoseok/repository/product/ExternalProductJpaRepository.kt
sns-service/data/jpa/src/main/kotlin/com/hyoseok/repository/product/ExternalProductRepositoryImpl.kt
sns-service/data/jpa/src/main/kotlin/com/hyoseok/repository/product/read/ExternalProductReadRepositoryImpl.kt
sns-service/data/jpa/src/test/kotlin/com/hyoseok/repository/RepositoryImplTests.kt
sns-service/data/jpa/src/test/kotlin/com/hyoseok/repository/product/ExternalProductRepositoryImplTests.kt
sns-service/data/jpa/src/test/kotlin/com/hyoseok/repository/sns/SnsRepositoryImplTests.kt
sns-service/domain/src/main/kotlin/com/hyoseok/product/entity/ExternalProduct.kt
sns-service/domain/src/main/kotlin/com/hyoseok/product/repository/ExternalProductRepository.kt
sns-service/domain/src/main/kotlin/com/hyoseok/product/repository/read/ExternalProductReadRepository.kt
sns-service/domain/src/main/kotlin/com/hyoseok/sns/entity/Sns.kt
sns-service/domain/src/test/kotlin/com/hyoseok/product/entity/ExternalProductTests.kt
sns-service/domain/src/test/kotlin/com/hyoseok/sns/entity/SnsTests.kt

- #39
- `application:command` 모듈 개발

[PR] product 도메인 개발

---

sns-service/application/command/requests.http
sns-service/application/command/src/main/kotlin/com/hyoseok/service/SnsFacadeService.kt
sns-service/application/command/src/main/kotlin/com/hyoseok/web/SnsController.kt
sns-service/application/query/src/main/kotlin/com/hyoseok/service/SnsFacadeService.kt
sns-service/application/query/src/main/kotlin/com/hyoseok/web/SnsController.kt
sns-service/data/jpa/src/main/kotlin/com/hyoseok/repository/sns/read/SnsReadRepositoryImpl.kt
sns-service/data/redis/src/main/kotlin/com/hyoseok/config/RedisZsetScores.kt
sns-service/data/redis/src/main/kotlin/com/hyoseok/repository/sns/read/SnsCacheReadRepositoryImpl.kt
sns-service/data/redis/src/test/kotlin/com/hyoseok/repository/SnsCacheRepositoryImplTests.kt

[PR] 레디스 관련 기능 버그 수정

---

sns-service/data/redis/src/main/kotlin/com/hyoseok/repository/sns/read/SnsCacheReadRepositoryImpl.kt
sns-service/data/redis/src/test/kotlin/com/hyoseok/repository/SnsCacheRepositoryImplTests.kt

[PR] mget 메서드 리팩토링

---

sns-service/application/command/requests.http
sns-service/application/command/src/main/kotlin/com/hyoseok/service/SnsCommandService.kt
sns-service/application/command/src/main/kotlin/com/hyoseok/service/SnsFacadeService.kt
sns-service/application/command/src/main/kotlin/com/hyoseok/web/SnsController.kt
sns-service/application/query/requests.http
sns-service/application/query/src/main/kotlin/com/hyoseok/service/SnsFacadeService.kt
sns-service/data/jpa/src/main/kotlin/com/hyoseok/repository/sns/SnsJpaRepository.kt
sns-service/data/jpa/src/main/kotlin/com/hyoseok/repository/sns/SnsRepositoryImpl.kt
sns-service/data/jpa/src/main/kotlin/com/hyoseok/repository/sns/read/SnsReadRepositoryImpl.kt
sns-service/data/jpa/src/test/kotlin/com/hyoseok/repository/sns/SnsRepositoryImplTests.kt
sns-service/data/redis/src/main/kotlin/com/hyoseok/config/RedisKeys.kt
sns-service/data/redis/src/main/kotlin/com/hyoseok/repository/sns/SnsCacheRepositoryImpl.kt
sns-service/data/redis/src/test/kotlin/com/hyoseok/repository/SnsCacheRepositoryImplTests.kt
sns-service/domain/src/main/kotlin/com/hyoseok/sns/repository/SnsCacheRepository.kt
sns-service/domain/src/main/kotlin/com/hyoseok/sns/repository/SnsRepository.kt

[PR] SNS 삭제 기능 개발

---

sns-service/data/redis/src/main/kotlin/com/hyoseok/repository/sns/SnsCacheRepositoryImpl.kt
sns-service/data/redis/src/test/kotlin/com/hyoseok/repository/SnsCacheRepositoryImplTests.kt
sns-service/domain/src/main/kotlin/com/hyoseok/sns/repository/SnsCacheRepository.kt

[PR] del, zremrangebyrank 메서드 구현

---

sns-service/application/command/src/main/kotlin/com/hyoseok/service/SnsFacadeService.kt
sns-service/application/query/src/main/kotlin/com/hyoseok/service/SnsFacadeService.kt
sns-service/data/redis/src/main/kotlin/com/hyoseok/config/RedisCommons.kt
sns-service/data/redis/src/main/kotlin/com/hyoseok/repository/sns/SnsCacheRepositoryImpl.kt
sns-service/data/redis/src/main/kotlin/com/hyoseok/repository/sns/read/SnsCacheReadRepositoryImpl.kt
sns-service/data/redis/src/test/kotlin/com/hyoseok/repository/SnsCacheRepositoryImplTests.kt
sns-service/domain/src/main/kotlin/com/hyoseok/sns/repository/SnsCacheRepository.kt
sns-service/domain/src/main/kotlin/com/hyoseok/sns/repository/read/SnsCacheReadRepository.kt

[PR] 캐시 저장 로직에 zremStringRangeByRank, del 메서드 추가

---

sns-feed-service/application/api/command/src/main/kotlin/com/hyoseok/SnsFeedCommandApplication.kt
sns-feed-service/application/api/command/src/main/resources/application.yml
sns-feed-service/application/api/query/src/main/kotlin/com/hyoseok/SnsFeedQueryApplication.kt
sns-feed-service/application/api/query/src/main/resources/application.yml
sns-feed-service/application/event-worker/feed/build.gradle.kts
sns-feed-service/application/event-worker/feed/src/main/kotlin/com/hyoseok/FeedEventWorker.kt
sns-feed-service/application/event-worker/feed/src/main/resources/application.yml
sns-feed-service/common/src/main/kotlin/com/hyoseok/constants/CircuitBreakerName.kt
sns-feed-service/common/src/main/kotlin/com/hyoseok/utils/Base62Util.kt
sns-feed-service/common/src/main/kotlin/com/hyoseok/utils/Crc32Util.kt
sns-feed-service/common/src/main/kotlin/com/hyoseok/utils/Sha256Util.kt
sns-feed-service/domain/src/main/kotlin/com/hyoseok/post/entity/Post.kt
sns-feed-service/domain/src/main/kotlin/com/hyoseok/post/entity/PostImage.kt
sns-feed-service/domain/src/main/kotlin/com/hyoseok/post/repository/PostReadRepository.kt
sns-feed-service/domain/src/main/kotlin/com/hyoseok/post/repository/PostRepository.kt
sns-feed-service/domain/src/test/kotlin/com/hyoseok/post/PostTests.kt

- #39
- Post, PostImage 엔티티 구현

[PR] Post 도메인 기능 개발

---

sns-feed-service/data/jpa/src/main/kotlin/com/hyoseok/config/jpa/JpaConfig.kt
sns-feed-service/data/jpa/src/main/kotlin/com/hyoseok/config/jpa/JpaQueryFactoryConfig.kt
sns-feed-service/data/jpa/src/main/kotlin/com/hyoseok/config/mysql/BasicDataSourceConfig.kt
sns-feed-service/data/jpa/src/main/kotlin/com/hyoseok/config/mysql/replication/ReplicationDataSourceConfig.kt
sns-feed-service/data/jpa/src/main/kotlin/com/hyoseok/config/mysql/replication/ReplicationDataSourceType.kt
sns-feed-service/data/jpa/src/main/kotlin/com/hyoseok/config/mysql/replication/ReplicationRoutingDataSource.kt
sns-feed-service/data/jpa/src/main/kotlin/com/hyoseok/config/mysql/replication/property/ReadProperty.kt
sns-feed-service/data/jpa/src/main/kotlin/com/hyoseok/config/mysql/replication/property/WriteProperty.kt
sns-feed-service/data/jpa/src/main/kotlin/com/hyoseok/entity/post/PostImageJpaEntity.kt
sns-feed-service/data/jpa/src/main/kotlin/com/hyoseok/entity/post/PostJpaEntity.kt
sns-feed-service/data/jpa/src/main/kotlin/com/hyoseok/exception/DataJpaMessage.kt
sns-feed-service/data/jpa/src/main/kotlin/com/hyoseok/repository/post/PostJpaRepository.kt
sns-feed-service/data/jpa/src/main/kotlin/com/hyoseok/repository/post/PostRepositoryImpl.kt
sns-feed-service/data/jpa/src/test/kotlin/com/hyoseok/repository/RepositoryImplTests.kt
sns-feed-service/data/jpa/src/test/kotlin/com/hyoseok/repository/post/PostRepositoryTests.kt
sns-feed-service/data/jpa/src/test/resources/application.yml
sns-feed-service/domain/src/main/kotlin/com/hyoseok/post/entity/Post.kt
sns-feed-service/domain/src/main/kotlin/com/hyoseok/post/entity/PostImage.kt

[PR] JPA 모듈에 Post 엔티티 저장 기능 구현

---

sns-feed-service/application/api/command/src/main/kotlin/com/hyoseok/exception/GlobalExceptionHandler.kt
sns-feed-service/application/api/command/src/main/kotlin/com/hyoseok/service/dto/PostCreateDto.kt
sns-feed-service/application/api/command/src/main/kotlin/com/hyoseok/service/post/PostService.kt
sns-feed-service/application/api/command/src/main/kotlin/com/hyoseok/web/response/ErrorResponse.kt
sns-feed-service/application/api/command/src/main/kotlin/com/hyoseok/web/response/FailResponse.kt
sns-feed-service/application/api/command/src/main/kotlin/com/hyoseok/web/response/SuccessResponse.kt
sns-feed-service/data/jpa/src/main/kotlin/com/hyoseok/entity/post/PostJpaEntity.kt
sns-feed-service/data/jpa/src/test/kotlin/com/hyoseok/repository/post/PostRepositoryTests.kt
sns-feed-service/data/redis/src/main/kotlin/com/hyoseok/config/RedisCommons.kt
sns-feed-service/data/redis/src/main/kotlin/com/hyoseok/config/RedisExpireTimes.kt
sns-feed-service/data/redis/src/main/kotlin/com/hyoseok/config/RedisKeys.kt
sns-feed-service/data/redis/src/main/kotlin/com/hyoseok/config/RedisMode.kt
sns-feed-service/data/redis/src/main/kotlin/com/hyoseok/config/post/RedisPostConfig.kt
sns-feed-service/data/redis/src/main/kotlin/com/hyoseok/config/post/RedisPostServerProperties.kt
sns-feed-service/data/redis/src/main/kotlin/com/hyoseok/config/post/RedisPostTemplateConfig.kt
sns-feed-service/data/redis/src/main/kotlin/com/hyoseok/exception/DataRedisMessage.kt
sns-feed-service/data/redis/src/main/kotlin/com/hyoseok/repository/AbstractCacheRepository.kt
sns-feed-service/data/redis/src/main/kotlin/com/hyoseok/repository/post/PostCacheReadRepositoryImpl.kt
sns-feed-service/data/redis/src/main/kotlin/com/hyoseok/repository/post/PostCacheRepositoryImpl.kt
sns-feed-service/data/redis/src/test/kotlin/com/hyoseok/config/RedisEmbbededServerConfig.kt
sns-feed-service/data/redis/src/test/kotlin/com/hyoseok/repository/post/PostCacheRepositoryTests.kt
sns-feed-service/data/redis/src/test/resources/application.yml
sns-feed-service/domain/src/main/kotlin/com/hyoseok/post/entity/Post.kt
sns-feed-service/domain/src/main/kotlin/com/hyoseok/post/entity/PostCache.kt
sns-feed-service/domain/src/main/kotlin/com/hyoseok/post/repository/PostCacheReadRepository.kt
sns-feed-service/domain/src/main/kotlin/com/hyoseok/post/repository/PostCacheRepository.kt
sns-feed-service/domain/src/test/kotlin/com/hyoseok/post/PostTests.kt

[PR] Redis 모듈에 Post 저장, 조회 기능 구현

---

sns-feed-service/application/api/command/src/main/kotlin/com/hyoseok/service/post/PostService.kt
sns-feed-service/data/redis/src/main/kotlin/com/hyoseok/config/RedisKeys.kt
sns-feed-service/data/redis/src/main/kotlin/com/hyoseok/repository/post/PostCacheReadRepositoryImpl.kt
sns-feed-service/data/redis/src/main/kotlin/com/hyoseok/repository/post/PostCacheRepositoryImpl.kt
sns-feed-service/data/redis/src/test/kotlin/com/hyoseok/repository/post/PostCacheRepositoryTests.kt
sns-feed-service/domain/src/main/kotlin/com/hyoseok/post/repository/PostCacheReadRepository.kt
sns-feed-service/domain/src/main/kotlin/com/hyoseok/post/repository/PostCacheRepository.kt

[PR] Redis의 SortedSet 커맨드 구현

---

sns-feed-service/application/api/command/requests.http
sns-feed-service/application/api/command/src/main/kotlin/com/hyoseok/web/PostController.kt
sns-feed-service/application/api/command/src/main/kotlin/com/hyoseok/web/request/PostCreateRequest.kt
sns-feed-service/application/api/command/src/main/resources/application.yml

[PR] Controller 구현

---

sns-feed-service/data/jpa/src/main/kotlin/com/hyoseok/entity/follow/FollowJpaEntity.kt
sns-feed-service/data/jpa/src/main/kotlin/com/hyoseok/repository/follow/FollowJpaRepository.kt
sns-feed-service/data/jpa/src/main/kotlin/com/hyoseok/repository/follow/FollowReadRepositoryImpl.kt
sns-feed-service/data/jpa/src/test/kotlin/com/hyoseok/repository/RepositoryImplTests.kt
sns-feed-service/data/jpa/src/test/kotlin/com/hyoseok/repository/follow/FollowRepositoryTests.kt
sns-feed-service/domain/src/main/kotlin/com/hyoseok/follow/entity/Follow.kt
sns-feed-service/domain/src/main/kotlin/com/hyoseok/follow/repository/FollowReadRepository.kt

[PR] Follow 조회 기능 개발

---

sns-feed-service/application/api/command/src/main/kotlin/com/hyoseok/service/dto/EventDto.kt
sns-feed-service/application/api/command/src/main/kotlin/com/hyoseok/service/post/PostCreateService.kt
sns-feed-service/application/api/command/src/main/kotlin/com/hyoseok/web/PostController.kt

- #39
- `application:api:command`

[PR] PostCreateService에 Feed 메세지 발행 템플릿 구현

---

sns-feed-service/application/api/command/build.gradle.kts
sns-feed-service/application/api/command/src/main/kotlin/com/hyoseok/service/post/PostCreateService.kt
sns-feed-service/application/api/command/src/main/resources/application.yml
sns-feed-service/data/jpa/src/main/kotlin/com/hyoseok/repository/follow/FollowReadRepositoryImpl.kt
sns-feed-service/data/jpa/src/test/kotlin/com/hyoseok/repository/follow/FollowRepositoryTests.kt
sns-feed-service/domain/src/main/kotlin/com/hyoseok/follow/repository/FollowReadRepository.kt
sns-feed-service/infrastructure/kafka/build.gradle.kts
sns-feed-service/infrastructure/kafka/src/main/kotlin/com/hyoseok/config/KafkaProducerConfig.kt
sns-feed-service/infrastructure/kafka/src/main/kotlin/com/hyoseok/config/KafkaTopics.kt
sns-feed-service/infrastructure/kafka/src/main/kotlin/com/hyoseok/publisher/KafkaProducer.kt

- #39
- `infrastructure:kafka` 모듈 개발

[PR] kafka 발행 기능 구현

---

sns-feed-service/application/api/command/src/main/kotlin/com/hyoseok/service/dto/EventDto.kt
sns-feed-service/application/api/command/src/main/kotlin/com/hyoseok/service/post/PostCreateService.kt
sns-feed-service/application/api/command/src/main/resources/application.yml
sns-feed-service/application/event-worker/feed/build.gradle.kts
sns-feed-service/application/event-worker/feed/src/main/kotlin/com/hyoseok/config/KafkaConsumerConcurrency.kt
sns-feed-service/application/event-worker/feed/src/main/kotlin/com/hyoseok/config/KafkaConsumerConfig.kt
sns-feed-service/application/event-worker/feed/src/main/kotlin/com/hyoseok/config/KafkaConsumerGroups.kt
sns-feed-service/application/event-worker/feed/src/main/kotlin/com/hyoseok/config/KafkaTopics.kt
sns-feed-service/application/event-worker/feed/src/main/kotlin/com/hyoseok/listener/KafkaSnsFeedConsumer.kt
sns-feed-service/application/event-worker/feed/src/main/kotlin/com/hyoseok/listener/dto/FollowerSendEventDto.kt
sns-feed-service/application/event-worker/feed/src/main/kotlin/com/hyoseok/service/FeedService.kt
sns-feed-service/application/event-worker/feed/src/main/resources/application.yml
sns-feed-service/data/redis/src/main/kotlin/com/hyoseok/config/RedisCommons.kt
sns-feed-service/data/redis/src/main/kotlin/com/hyoseok/config/RedisKeys.kt
sns-feed-service/data/redis/src/main/kotlin/com/hyoseok/config/feed/RedisFeedConfig.kt
sns-feed-service/data/redis/src/main/kotlin/com/hyoseok/config/feed/RedisFeedServerProperties.kt
sns-feed-service/data/redis/src/main/kotlin/com/hyoseok/config/feed/RedisFeedTemplateConfig.kt
sns-feed-service/data/redis/src/main/kotlin/com/hyoseok/repository/feed/FeedCacheReadRepositoryImpl.kt
sns-feed-service/data/redis/src/main/kotlin/com/hyoseok/repository/feed/FeedCacheRepositoryImpl.kt
sns-feed-service/data/redis/src/test/kotlin/com/hyoseok/config/RedisFeedEmbbededServerConfig.kt
sns-feed-service/data/redis/src/test/kotlin/com/hyoseok/config/RedisPostEmbbededServerConfig.kt
sns-feed-service/data/redis/src/test/kotlin/com/hyoseok/repository/feed/FeedCacheRepositoryTests.kt
sns-feed-service/data/redis/src/test/kotlin/com/hyoseok/repository/post/PostCacheRepositoryTests.kt
sns-feed-service/data/redis/src/test/resources/application.yml
sns-feed-service/domain/src/main/kotlin/com/hyoseok/feed/entity/FeedCache.kt
sns-feed-service/domain/src/main/kotlin/com/hyoseok/feed/repository/FeedCacheReadRepository.kt
sns-feed-service/domain/src/main/kotlin/com/hyoseok/feed/repository/FeedCacheRepository.kt

- #39
- `application:event-worker:feed` 모듈 개발
- `data:redis` 모듈 개발

[PR] KafkaConsumerWorker 및 Redis FeedCache 저장 기능 개발

---

sns-feed-service/application/api/command-server/requests.http
sns-feed-service/application/api/command-server/src/main/kotlin/com/hyoseok/service/dto/MemberDto.kt
sns-feed-service/application/api/command-server/src/main/kotlin/com/hyoseok/service/member/MemberService.kt
sns-feed-service/application/api/command-server/src/main/kotlin/com/hyoseok/web/MemberController.kt
sns-feed-service/application/api/command-server/src/main/kotlin/com/hyoseok/web/request/MemberCreateRequest.kt
sns-feed-service/data/jpa/src/main/kotlin/com/hyoseok/entity/member/MemberJpaEntity.kt
sns-feed-service/data/jpa/src/main/kotlin/com/hyoseok/exception/DataJpaMessage.kt
sns-feed-service/data/jpa/src/main/kotlin/com/hyoseok/repository/member/MemberJpaRepository.kt
sns-feed-service/data/jpa/src/main/kotlin/com/hyoseok/repository/member/MemberReadRepositoryImpl.kt
sns-feed-service/data/jpa/src/main/kotlin/com/hyoseok/repository/member/MemberRepositoryImpl.kt
sns-feed-service/data/jpa/src/test/kotlin/com/hyoseok/repository/RepositoryImplTests.kt
sns-feed-service/data/jpa/src/test/kotlin/com/hyoseok/repository/member/MemberRepositoryTests.kt
sns-feed-service/domain/src/main/kotlin/com/hyoseok/member/entity/Member.kt
sns-feed-service/domain/src/main/kotlin/com/hyoseok/member/repository/MemberReadRepository.kt
sns-feed-service/domain/src/main/kotlin/com/hyoseok/member/repository/MemberRepository.kt

- #39
- `application:api:command-server` 모듈 개발

[PR] Member 도메인 개발

---

sns-feed-service/application/api/command-server/requests.http
sns-feed-service/application/api/command-server/src/main/kotlin/com/hyoseok/service/follow/FollowService.kt
sns-feed-service/application/api/command-server/src/main/kotlin/com/hyoseok/service/post/PostCreateService.kt
sns-feed-service/data/jpa/src/main/kotlin/com/hyoseok/repository/member/MemberReadRepositoryImpl.kt
sns-feed-service/data/jpa/src/test/kotlin/com/hyoseok/repository/member/MemberRepositoryTests.kt
sns-feed-service/domain/src/main/kotlin/com/hyoseok/member/repository/MemberReadRepository.kt

[PR] 회원이 존재하지 않는 경우에 대한 예외로직 추가

---

sns-feed-service/application/api/command-server/requests.http
sns-feed-service/data/redis/feed/src/main/kotlin/com/hyoseok/config/RedisExpireTimes.kt
sns-feed-service/data/redis/feed/src/main/kotlin/com/hyoseok/repository/FeedCacheReadRepositoryImpl.kt
sns-feed-service/data/redis/feed/src/main/kotlin/com/hyoseok/repository/FeedCacheRepositoryImpl.kt
sns-feed-service/data/redis/feed/src/test/kotlin/com/hyoseok/repository/FeedCacheRepositoryTests.kt
sns-feed-service/domain/src/main/kotlin/com/hyoseok/feed/repository/FeedCacheReadRepository.kt

- #39
- `data:redis:feed` 모듈 개발

[PR] Feed 캐시에 만료 시간 설정

---

sns-feed-service/application/api/query-server/requests.http
sns-feed-service/application/api/query-server/src/main/kotlin/com/hyoseok/web/FeedController.kt
sns-feed-service/application/api/query-server/src/main/resources/application.yml

- #39 
- `application:api:query` 모듈 개발

[PR] query 모듈 controller 개발

---

sns-feed-service/application/api/query-server/src/main/kotlin/com/hyoseok/service/feed/FeedService.kt
sns-feed-service/data/jpa/src/main/kotlin/com/hyoseok/entity/follow/FollowJpaEntity.kt
sns-feed-service/data/jpa/src/main/kotlin/com/hyoseok/repository/post/PostReadRepositoryImpl.kt
sns-feed-service/data/jpa/src/test/kotlin/com/hyoseok/repository/post/PostRepositoryTests.kt
sns-feed-service/domain/src/main/kotlin/com/hyoseok/post/repository/PostReadRepository.kt

- #39 
- `application:api:query`
- `data:jpa`
- `domain`

[PR] 피드 서비스 리팩토링

---

sns-feed-service/application/api/query-server/requests.http
sns-feed-service/application/api/query-server/src/main/kotlin/com/hyoseok/service/feed/FeedService.kt
sns-feed-service/application/api/query-server/src/main/kotlin/com/hyoseok/service/post/PostService.kt
sns-feed-service/application/api/query-server/src/main/kotlin/com/hyoseok/web/PostController.kt
sns-feed-service/data/jpa/src/main/kotlin/com/hyoseok/repository/post/PostJpaRepository.kt
sns-feed-service/data/jpa/src/main/kotlin/com/hyoseok/repository/post/PostReadRepositoryImpl.kt
sns-feed-service/data/jpa/src/test/kotlin/com/hyoseok/repository/post/PostRepositoryTests.kt
sns-feed-service/data/redis/post/src/main/kotlin/com/hyoseok/repository/PostCacheReadRepositoryImpl.kt
sns-feed-service/domain/src/main/kotlin/com/hyoseok/post/repository/PostCacheReadRepository.kt
sns-feed-service/domain/src/main/kotlin/com/hyoseok/post/repository/PostReadRepository.kt

- #39
- `application:api:query` 모듈 개발
- `data:redis` 모듈 개발

[PR] 나의 게시물 리스트 조회 기능 개발

---

sns-feed-service/application/api/command-server/src/main/resources/application.yml
sns-feed-service/infrastructure/kafka/src/main/kotlin/com/hyoseok/config/KafkaProducerConfig.kt
sns-feed-service/infrastructure/kafka/src/main/kotlin/com/hyoseok/publisher/KafkaProducer.kt

[PR] kafka 모듈 설정 방식 추가

---

sns-feed-service/application/api/command-server/src/main/resources/application.yml
sns-feed-service/application/api/query-server/src/main/resources/application.yml
sns-feed-service/application/event-worker/feed-server/src/main/resources/application.yml
sns-feed-service/data/jpa/src/main/kotlin/com/hyoseok/config/jpa/JpaConfig.kt
sns-feed-service/data/jpa/src/main/kotlin/com/hyoseok/config/jpa/JpaQueryFactoryConfig.kt
sns-feed-service/data/jpa/src/main/kotlin/com/hyoseok/config/mysql/BasicDataSourceConfig.kt
sns-feed-service/data/jpa/src/main/kotlin/com/hyoseok/config/mysql/replication/SnsReplicationDataSourceConfig.kt
sns-feed-service/data/jpa/src/main/kotlin/com/hyoseok/config/mysql/replication/property/ReadProperty.kt
sns-feed-service/data/jpa/src/main/kotlin/com/hyoseok/config/mysql/replication/property/WriteProperty.kt
sns-feed-service/data/jpa/src/main/kotlin/com/hyoseok/repository/follow/FollowReadRepositoryImpl.kt
sns-feed-service/data/jpa/src/main/kotlin/com/hyoseok/repository/follow/FollowRepositoryImpl.kt
sns-feed-service/data/jpa/src/main/kotlin/com/hyoseok/repository/member/MemberReadRepositoryImpl.kt
sns-feed-service/data/jpa/src/main/kotlin/com/hyoseok/repository/member/MemberRepositoryImpl.kt
sns-feed-service/data/jpa/src/main/kotlin/com/hyoseok/repository/post/PostReadRepositoryImpl.kt
sns-feed-service/data/jpa/src/main/kotlin/com/hyoseok/repository/post/PostRepositoryImpl.kt
sns-feed-service/data/jpa/src/test/resources/application.yml
sns-feed-service/infrastructure/kafka/src/main/kotlin/com/hyoseok/config/KafkaProducerConfig.kt

[PR] DataSource, JPA 설정 방식 변경

---

sns-feed-service/application/api/command-server/src/main/kotlin/com/hyoseok/service/follow/FollowService.kt
sns-feed-service/data/jpa/src/main/kotlin/com/hyoseok/repository/follow/FollowJpaRepository.kt
sns-feed-service/data/jpa/src/main/kotlin/com/hyoseok/repository/follow/FollowReadRepositoryImpl.kt
sns-feed-service/data/jpa/src/test/kotlin/com/hyoseok/repository/follow/FollowRepositoryTests.kt
sns-feed-service/domain/src/main/kotlin/com/hyoseok/exception/DomainExceptionMessage.kt
sns-feed-service/domain/src/main/kotlin/com/hyoseok/follow/entity/Follow.kt
sns-feed-service/domain/src/main/kotlin/com/hyoseok/follow/repository/FollowReadRepository.kt
sns-feed-service/domain/src/test/kotlin/com/hyoseok/follow/FollowTests.kt

[PR] 최대 Follow 제한 기능 추가

---

sns-feed-service/domain/src/main/kotlin/com/hyoseok/exception/DomainExceptionMessage.kt
sns-feed-service/domain/src/main/kotlin/com/hyoseok/follow/entity/Follow.kt
sns-feed-service/domain/src/test/kotlin/com/hyoseok/follow/FollowTests.kt

[PR] followerId, followeeId 같은 경우에 대한 예외 로직 추가

---

sns-feed-service/data/redis/src/main/kotlin/com/hyoseok/repository/feed/FeedCacheReadRepositoryImpl.kt
sns-feed-service/data/redis/src/main/kotlin/com/hyoseok/repository/feed/FeedCacheRepositoryImpl.kt
sns-feed-service/data/redis/src/test/kotlin/com/hyoseok/repository/feed/FeedCacheRepositoryTests.kt
sns-feed-service/domain/src/main/kotlin/com/hyoseok/feed/repository/FeedCacheReadRepository.kt
sns-feed-service/domain/src/main/kotlin/com/hyoseok/feed/repository/FeedCacheRepository.kt
sns-feed-service/infrastructure/kafka/src/main/kotlin/com/hyoseok/config/KafkaProducerConfig.kt

[PR] Score 관련해서 ZSET 조회, 삭제 기능 개발

---

sns-feed-service/application/api/command-server/src/main/kotlin/com/hyoseok/service/follow/FollowService.kt
sns-feed-service/application/api/command-server/src/main/kotlin/com/hyoseok/service/member/MemberService.kt
sns-feed-service/application/api/command-server/src/main/kotlin/com/hyoseok/service/post/PostCreateService.kt
sns-feed-service/data/jpa/src/main/kotlin/com/hyoseok/config/jpa/JpaConfig.kt
sns-feed-service/data/jpa/src/main/kotlin/com/hyoseok/repository/follow/FollowReadRepositoryImpl.kt
sns-feed-service/data/jpa/src/main/kotlin/com/hyoseok/repository/follow/FollowRepositoryImpl.kt
sns-feed-service/data/jpa/src/main/kotlin/com/hyoseok/repository/member/MemberReadRepositoryImpl.kt
sns-feed-service/data/jpa/src/main/kotlin/com/hyoseok/repository/member/MemberRepositoryImpl.kt
sns-feed-service/data/jpa/src/main/kotlin/com/hyoseok/repository/post/PostReadRepositoryImpl.kt
sns-feed-service/data/jpa/src/main/kotlin/com/hyoseok/repository/post/PostRepositoryImpl.kt

- #87
- `data:jpa` 모듈 리팩토링
- `application:api:command` 모듈 리팩토링

[PR] jpaTransactionManager Bean 주입 명시

---

sns-feed-service/data/jpa/src/main/kotlin/com/hyoseok/config/datasource/BasicDataSourceConfig.kt
sns-feed-service/data/jpa/src/main/kotlin/com/hyoseok/config/datasource/replication/ReplicationDataSourceType.kt
sns-feed-service/data/jpa/src/main/kotlin/com/hyoseok/config/datasource/replication/ReplicationRoutingDataSource.kt
sns-feed-service/data/jpa/src/main/kotlin/com/hyoseok/config/datasource/replication/SnsReplicationDataSourceConfig.kt
sns-feed-service/data/jpa/src/main/kotlin/com/hyoseok/config/datasource/replication/property/ReadProperty.kt
sns-feed-service/data/jpa/src/main/kotlin/com/hyoseok/config/datasource/replication/property/WriteProperty.kt
sns-feed-service/data/jpa/src/test/kotlin/com/hyoseok/repository/RepositoryImplTests.kt

[PR] 패키지명을 datasource 로 변경

---

coupon-service/domain/build.gradle.kts
coupon-service/domain/src/main/kotlin/com/hyoseok/coupon/entity/Coupon.kt
coupon-service/domain/src/main/kotlin/com/hyoseok/coupon/entity/CouponIssued.kt
coupon-service/domain/src/main/kotlin/com/hyoseok/coupon/repository/CouponIssuedRepository.kt
coupon-service/domain/src/main/kotlin/com/hyoseok/coupon/repository/CouponRepository.kt
coupon-service/domain/src/main/kotlin/com/hyoseok/member/entity/Member.kt
coupon-service/domain/src/main/kotlin/com/hyoseok/member/repository/MemberRepository.kt
coupon-service/domain/src/test/kotlin/com/hyoseok/coupon/CouponIssuedTests.kt
coupon-service/domain/src/test/kotlin/com/hyoseok/coupon/CouponTests.kt
coupon-service/domain/src/test/kotlin/com/hyoseok/member/MemberTests.kt
docker/redis/docker-coupon-compose.yml
settings.gradle.kts

[PR] Coupon Service 도메인 모듈 개발

---

coupon-service/data/jpa/build.gradle.kts
coupon-service/data/jpa/src/main/kotlin/com/hyoseok/config/datasource/DataSourceConfig.kt
coupon-service/data/jpa/src/main/kotlin/com/hyoseok/config/datasource/replication/ReplicationDataSourceConfig.kt
coupon-service/data/jpa/src/main/kotlin/com/hyoseok/config/datasource/replication/ReplicationDataSourceType.kt
coupon-service/data/jpa/src/main/kotlin/com/hyoseok/config/datasource/replication/ReplicationRoutingDataSource.kt
coupon-service/data/jpa/src/main/kotlin/com/hyoseok/config/datasource/replication/property/ReadProperty.kt
coupon-service/data/jpa/src/main/kotlin/com/hyoseok/config/datasource/replication/property/WriteProperty.kt
coupon-service/data/jpa/src/main/kotlin/com/hyoseok/config/jpa/JpaConfig.kt
coupon-service/data/jpa/src/main/kotlin/com/hyoseok/config/jpa/JpaQueryFactoryConfig.kt
coupon-service/data/jpa/src/main/kotlin/com/hyoseok/entity/coupon/CouponEntity.kt
coupon-service/data/jpa/src/main/kotlin/com/hyoseok/entity/coupon/CouponIssuedEntity.kt
coupon-service/data/jpa/src/main/kotlin/com/hyoseok/entity/member/MemberEntity.kt
coupon-service/data/jpa/src/main/kotlin/com/hyoseok/repository/coupon/CouponIssuedJpaRepository.kt
coupon-service/data/jpa/src/main/kotlin/com/hyoseok/repository/coupon/CouponIssuedJpaRepositoryAdapter.kt
coupon-service/data/jpa/src/main/kotlin/com/hyoseok/repository/coupon/CouponJpaRepository.kt
coupon-service/data/jpa/src/main/kotlin/com/hyoseok/repository/coupon/CouponJpaRepositoryAdapter.kt
coupon-service/data/jpa/src/main/kotlin/com/hyoseok/repository/member/MemberJpaRepository.kt
coupon-service/data/jpa/src/main/kotlin/com/hyoseok/repository/member/MemberJpaRepositoryAdapter.kt
coupon-service/data/jpa/src/test/kotlin/com/hyoseok/JpaRepositoryAdapterTests.kt
coupon-service/data/jpa/src/test/kotlin/com/hyoseok/repository/coupon/CouponIssuedJpaRepositoryAdapterTests.kt
coupon-service/data/jpa/src/test/kotlin/com/hyoseok/repository/coupon/CouponJpaRepositoryAdapterTests.kt
coupon-service/data/jpa/src/test/kotlin/com/hyoseok/repository/member/MemberJpaRepositoryAdapterTests.kt
coupon-service/data/jpa/src/test/resources/application.yml
coupon-service/domain/src/main/kotlin/com/hyoseok/coupon/entity/Coupon.kt
coupon-service/domain/src/main/kotlin/com/hyoseok/coupon/entity/CouponIssued.kt
coupon-service/domain/src/main/kotlin/com/hyoseok/member/entity/Member.kt

[PR] data:jpa 모듈 개발

---

coupon-service/application/coupon-command-api/build.gradle.kts
coupon-service/application/coupon-command-api/src/main/kotlin/com/hyoseok/CouponCommandApiApplication.kt
coupon-service/application/coupon-command-api/src/main/kotlin/com/hyoseok/controller/coupon/CouponController.kt
coupon-service/application/coupon-command-api/src/main/kotlin/com/hyoseok/controller/member/MemberController.kt
coupon-service/application/coupon-command-api/src/main/kotlin/com/hyoseok/controller/request/CouponCreateRequest.kt
coupon-service/application/coupon-command-api/src/main/kotlin/com/hyoseok/controller/request/MemberCreateRequest.kt
coupon-service/application/coupon-command-api/src/main/kotlin/com/hyoseok/exception/GlobalExceptionHandler.kt
coupon-service/application/coupon-command-api/src/main/kotlin/com/hyoseok/service/coupon/CouponService.kt
coupon-service/application/coupon-command-api/src/main/kotlin/com/hyoseok/service/dto/CouponServiceDto.kt
coupon-service/application/coupon-command-api/src/main/kotlin/com/hyoseok/service/dto/MemberServiceDto.kt
coupon-service/application/coupon-command-api/src/main/kotlin/com/hyoseok/service/member/MemberService.kt
coupon-service/application/coupon-command-api/src/main/resources/application.yml
coupon-service/common/build.gradle.kts
coupon-service/common/src/main/kotlin/com/hyoseok/response/ErrorResponse.kt
coupon-service/common/src/main/kotlin/com/hyoseok/response/FailResponse.kt
coupon-service/common/src/main/kotlin/com/hyoseok/response/SuccessResponse.kt

[PR] application:coupon-command-cpi 모듈 개발

---

coupon-service/data/redis/build.gradle.kts
coupon-service/data/redis/src/main/kotlin/com/hyoseok/config/RedisKey.kt
coupon-service/data/redis/src/main/kotlin/com/hyoseok/config/RedisMode.kt
coupon-service/data/redis/src/main/kotlin/com/hyoseok/config/coupon/RedisCouponConfig.kt
coupon-service/data/redis/src/main/kotlin/com/hyoseok/config/coupon/RedisCouponTemplateConfig.kt
coupon-service/data/redis/src/main/kotlin/com/hyoseok/exception/DataRedisMessage.kt
coupon-service/data/redis/src/main/kotlin/com/hyoseok/repository/coupon/CouponRedisRepositoryImpl.kt
coupon-service/data/redis/src/test/kotlin/com/hyoseok/config/coupon/RedisCouponEmbbededServerConfig.kt
coupon-service/data/redis/src/test/kotlin/com/hyoseok/repository/CouponRedisRepositoryImplTests.kt
coupon-service/data/redis/src/test/resources/application.yml
coupon-service/domain/src/main/kotlin/com/hyoseok/coupon/entity/CouponIssued.kt
coupon-service/domain/src/main/kotlin/com/hyoseok/coupon/repository/CouponRedisRepository.kt

[PR] data:redis 모듈 개발

---

coupon-service/application/coupon-command-api/build.gradle.kts
coupon-service/application/coupon-command-api/src/main/kotlin/com/hyoseok/exception/CommandApiMessage.kt
coupon-service/application/coupon-command-api/src/main/kotlin/com/hyoseok/service/coupon/CouponIssuedService.kt
coupon-service/application/coupon-command-api/src/main/kotlin/com/hyoseok/service/dto/CouponIssuedServiceDto.kt
coupon-service/application/coupon-command-api/src/main/kotlin/com/hyoseok/service/dto/CouponServiceDto.kt
coupon-service/application/coupon-command-api/src/main/kotlin/com/hyoseok/service/dto/MemberServiceDto.kt
coupon-service/application/coupon-command-api/src/main/resources/application.yml
coupon-service/application/coupon-command-api/src/test/kotlin/com/hyoseok/service/coupon/CouponServiceTests.kt
coupon-service/application/coupon-command-api/src/test/kotlin/com/hyoseok/service/member/MemberServiceTests.kt
coupon-service/application/coupon-command-api/src/test/resources/application.yml
coupon-service/data/redis/src/test/kotlin/com/hyoseok/repository/coupon/CouponRedisRepositoryImplTests.kt
coupon-service/domain/src/main/kotlin/com/hyoseok/coupon/entity/Coupon.kt
coupon-service/domain/src/main/kotlin/com/hyoseok/coupon/entity/CouponIssued.kt
coupon-service/domain/src/main/kotlin/com/hyoseok/member/entity/Member.kt

[PR] 쿠폰 발급 기능에 대한 프로토타입 개발

---

coupon-service/infrastructure/kafka/build.gradle.kts
coupon-service/infrastructure/kafka/src/main/kotlin/com/hyoseok/config/KafkaProducerConfig.kt
coupon-service/infrastructure/kafka/src/main/kotlin/com/hyoseok/publisher/KafkaProducer.kt
coupon-service/infrastructure/kafka/src/main/kotlin/com/hyoseok/publisher/KafkaProducerCallback.kt

[PR] infrastructure:kafka 모듈 개발

---

coupon-service/application/coupon-command-api/build.gradle.kts
coupon-service/application/coupon-command-api/src/main/kotlin/com/hyoseok/controller/request/CouponCreateRequest.kt
coupon-service/application/coupon-command-api/src/main/kotlin/com/hyoseok/service/coupon/CouponIssuedService.kt
coupon-service/application/coupon-command-api/src/main/kotlin/com/hyoseok/service/dto/CouponIssuedServiceDto.kt
coupon-service/application/coupon-command-api/src/main/kotlin/com/hyoseok/service/dto/CouponServiceDto.kt
coupon-service/application/coupon-command-api/src/main/resources/application.yml
coupon-service/application/coupon-command-api/src/test/kotlin/com/hyoseok/service/coupon/CouponServiceTests.kt
coupon-service/data/jpa/src/main/kotlin/com/hyoseok/entity/coupon/CouponEntity.kt
coupon-service/data/jpa/src/main/kotlin/com/hyoseok/entity/coupon/CouponIssuedFailEntity.kt
coupon-service/data/jpa/src/main/kotlin/com/hyoseok/exception/DataJpaMessage.kt
coupon-service/data/jpa/src/main/kotlin/com/hyoseok/repository/coupon/CouponIssuedFailJpaRepository.kt
coupon-service/data/jpa/src/main/kotlin/com/hyoseok/repository/coupon/CouponIssuedFailJpaRepositoryAdapter.kt
coupon-service/data/jpa/src/main/kotlin/com/hyoseok/repository/coupon/CouponJpaReadRepositoryAdapter.kt
coupon-service/data/jpa/src/test/kotlin/com/hyoseok/JpaRepositoryAdapterTests.kt
coupon-service/data/jpa/src/test/kotlin/com/hyoseok/repository/coupon/CouponIssuedFailJpaRepositoryAdapterTests.kt
coupon-service/data/jpa/src/test/kotlin/com/hyoseok/repository/coupon/CouponJpaRepositoryAdapterTests.kt
coupon-service/data/jpa/src/test/kotlin/com/hyoseok/repository/member/MemberJpaRepositoryAdapterTests.kt
coupon-service/domain/src/main/kotlin/com/hyoseok/coupon/entity/Coupon.kt
coupon-service/domain/src/main/kotlin/com/hyoseok/coupon/entity/CouponIssuedFail.kt
coupon-service/domain/src/main/kotlin/com/hyoseok/coupon/repository/CouponIssuedFailRepository.kt
coupon-service/domain/src/main/kotlin/com/hyoseok/coupon/repository/CouponReadRepository.kt
coupon-service/domain/src/main/kotlin/com/hyoseok/service/MessageBrokerProducer.kt
coupon-service/domain/src/test/kotlin/com/hyoseok/coupon/CouponTests.kt
coupon-service/infrastructure/kafka/build.gradle.kts
coupon-service/infrastructure/kafka/src/main/kotlin/com/hyoseok/exception/KafkaProducerSendFailedException.kt
coupon-service/infrastructure/kafka/src/main/kotlin/com/hyoseok/publisher/KafkaProducer.kt

[PR] 쿠폰 발행 기능 개발

---

coupon-service/application/coupon-command-api/src/main/kotlin/com/hyoseok/exception/CommandApiMessage.kt
coupon-service/application/coupon-command-api/src/main/kotlin/com/hyoseok/service/coupon/CouponIssuedService.kt
coupon-service/application/coupon-command-api/src/main/kotlin/com/hyoseok/service/dto/CouponIssuedServiceDto.kt
coupon-service/application/coupon-command-api/src/test/kotlin/com/hyoseok/service/coupon/CouponIssuedServiceTests.kt
coupon-service/data/redis/src/main/kotlin/com/hyoseok/exception/DataRedisMessage.kt
coupon-service/data/redis/src/main/kotlin/com/hyoseok/repository/coupon/CouponRedisRepositoryImpl.kt
coupon-service/data/redis/src/test/kotlin/com/hyoseok/repository/coupon/CouponRedisRepositoryImplTests.kt
coupon-service/domain/src/main/kotlin/com/hyoseok/coupon/entity/CouponIssued.kt
coupon-service/domain/src/main/kotlin/com/hyoseok/coupon/repository/CouponRedisRepository.kt

- #91
- 쿠폰 발급시, Redis 관련 기능을 `data:redis` 모듈에서 구현

[PR] 쿠폰 발급 기능 리팩토링

---

coupon-service/application/coupon-command-api/src/main/kotlin/com/hyoseok/coupon/controller/CouponController.kt
coupon-service/application/coupon-command-api/src/main/kotlin/com/hyoseok/member/controller/MemberController.kt
coupon-service/application/coupon-command-api/src/test/kotlin/com/hyoseok/coupon/integration/CouponIntegrationTests.kt
coupon-service/application/coupon-command-api/src/test/kotlin/com/hyoseok/member/integration/MemberIntegrationTests.kt
coupon-service/application/coupon-command-api/src/test/resources/application.yml

[PR] 쿠폰 이슈 통합 테스트 코드 추가

---

coupon-service/application/coupon-command-api/src/test/kotlin/com/hyoseok/config/IntegrationTests.kt
coupon-service/application/coupon-command-api/src/test/kotlin/com/hyoseok/coupon/integration/CouponIntegrationTests.kt
coupon-service/application/coupon-command-api/src/test/kotlin/com/hyoseok/member/integration/MemberIntegrationTests.kt

[PR] 공통으로 사용하는 설정을 인터페이스로 분리

---

coupon-service/application/coupon-command-api/src/main/resources/application.yml
coupon-service/application/coupon-command-api/src/test/resources/application.yml
coupon-service/data/jpa/src/main/kotlin/com/hyoseok/coupon/entity/CouponIssuedEntity.kt
coupon-service/data/jpa/src/main/kotlin/com/hyoseok/coupon/repository/CouponIssuedJpaReadRepositoryAdapter.kt
coupon-service/data/jpa/src/main/kotlin/com/hyoseok/coupon/repository/CouponIssuedJpaRepository.kt
coupon-service/data/jpa/src/test/kotlin/com/hyoseok/config/JpaRepositoryAdapterTests.kt
coupon-service/data/jpa/src/test/kotlin/com/hyoseok/coupon/repository/CouponIssuedJpaRepositoryAdapterTests.kt
coupon-service/domain/src/main/kotlin/com/hyoseok/coupon/repository/CouponIssuedReadRepository.kt
coupon-service/infrastructure/kafka/src/main/kotlin/com/hyoseok/publisher/KafkaCouponProducer.kt

[PR] CouponIssuedReadRepository 조회 기능 개발

---

coupon-service/application/coupon-issue-event-worker/build.gradle.kts
coupon-service/application/coupon-issue-event-worker/src/main/kotlin/com/hyoseok/CouponIssuedEventWorker.kt
coupon-service/application/coupon-issue-event-worker/src/main/kotlin/com/hyoseok/config/KafkaConsumerConfig.kt
coupon-service/application/coupon-issue-event-worker/src/main/kotlin/com/hyoseok/consumer/KafkaCouponIssuedConsumer.kt
coupon-service/application/coupon-issue-event-worker/src/main/kotlin/com/hyoseok/consumer/dto/CouponIssuedCreateDto.kt
coupon-service/application/coupon-issue-event-worker/src/main/kotlin/com/hyoseok/exception/CouponIssuedEventWorkerMessage.kt
coupon-service/application/coupon-issue-event-worker/src/main/kotlin/com/hyoseok/service/CouponIssuedService.kt
coupon-service/application/coupon-issue-event-worker/src/main/resources/application.yml
coupon-service/application/coupon-issue-event-worker/src/test/kotlin/com/hyoseok/config/TestKafkaProducer.kt
coupon-service/application/coupon-issue-event-worker/src/test/kotlin/com/hyoseok/listener/KafkaCouponIssuedConsumerTests.kt
coupon-service/application/coupon-issue-event-worker/src/test/kotlin/com/hyoseok/service/CouponIssuedServiceTests.kt
coupon-service/application/coupon-issue-event-worker/src/test/resources/application.yml

feat: coupon-issue-event-worker 모듈 개발

---

coupon-service/application/coupon-issue-event-worker/src/test/kotlin/com/hyoseok/consumer/KafkaCouponIssuedConsumerTests.kt

[PR] 패키지 이름 변경

---

coupon-service/data/jpa/src/main/kotlin/com/hyoseok/coupon/entity/CouponEntity.kt
coupon-service/data/jpa/src/main/kotlin/com/hyoseok/coupon/entity/CouponIssuedEntity.kt
coupon-service/data/jpa/src/main/kotlin/com/hyoseok/coupon/entity/CouponIssuedFailEntity.kt
coupon-service/data/jpa/src/main/kotlin/com/hyoseok/coupon/repository/CouponIssuedJpaRepositoryAdapter.kt
coupon-service/data/jpa/src/main/kotlin/com/hyoseok/member/entity/MemberEntity.kt
coupon-service/data/jpa/src/test/kotlin/com/hyoseok/coupon/repository/CouponIssuedJpaRepositoryAdapterTests.kt

[PR] CouponIssued 테이블 유니크 키 추가

---

coupon-service/data/jpa/src/test/kotlin/com/hyoseok/coupon/repository/CouponIssuedJpaRepositoryAdapterTests.kt

[PR] 테스트 코드 보완

---

coupon-service/application/coupon-issue-event-worker/src/main/kotlin/com/hyoseok/consumer/KafkaCouponIssuedConsumer.kt
coupon-service/application/coupon-issue-event-worker/src/main/kotlin/com/hyoseok/exception/KafkaCouponIssuedErrorHandler.kt
coupon-service/application/coupon-issue-event-worker/src/test/kotlin/com/hyoseok/config/TestKafkaProducer.kt
coupon-service/application/coupon-issue-event-worker/src/test/kotlin/com/hyoseok/consumer/KafkaCouponIssuedConsumerTests.kt
coupon-service/data/jpa/src/main/kotlin/com/hyoseok/coupon/repository/CouponIssuedJpaRepositoryAdapter.kt
coupon-service/data/jpa/src/test/kotlin/com/hyoseok/coupon/repository/CouponIssuedJpaRepositoryAdapterTests.kt
coupon-service/infrastructure/kafka/src/main/kotlin/com/hyoseok/publisher/KafkaCouponProducer.kt

- #91
- 중복 쿠폰 발급시, 그냥 `commitSync()` 처리

[PR] 컨슈머 워커 예외 핸들러 추가

---

coupon-service/application/coupon-command-api/src/main/kotlin/com/hyoseok/coupon/service/CouponIssuedService.kt
coupon-service/application/coupon-command-api/src/main/kotlin/com/hyoseok/coupon/service/dto/CouponIssuedServiceDto.kt
coupon-service/application/coupon-command-api/src/test/kotlin/com/hyoseok/coupon/integration/CouponIntegrationTests.kt
coupon-service/application/coupon-command-api/src/test/kotlin/com/hyoseok/coupon/service/CouponIssuedServiceTests.kt
coupon-service/application/coupon-issue-event-worker/src/test/kotlin/com/hyoseok/consumer/KafkaCouponIssuedConsumerTests.kt
coupon-service/data/redis/src/main/kotlin/com/hyoseok/coupon/repository/CouponRedisRepositoryImpl.kt
coupon-service/data/redis/src/test/kotlin/com/hyoseok/coupon/repository/CouponRedisRepositoryImplTests.kt
coupon-service/domain/src/main/kotlin/com/hyoseok/coupon/entity/CouponIssued.kt
coupon-service/domain/src/main/kotlin/com/hyoseok/coupon/entity/enum/CouponIssuedStatus.kt

[PR] ConponIssuedStatus Enum 클래스 생성

---

coupon-service/application/coupon-command-api/src/main/kotlin/com/hyoseok/coupon/service/CouponIssuedService.kt
coupon-service/application/coupon-command-api/src/main/kotlin/com/hyoseok/coupon/service/dto/CouponIssuedServiceDto.kt
coupon-service/application/coupon-issue-event-worker/src/main/kotlin/com/hyoseok/consumer/KafkaCouponIssuedErrorHandler.kt
coupon-service/application/coupon-issue-event-worker/src/test/kotlin/com/hyoseok/consumer/KafkaCouponIssuedConsumerTests.kt
coupon-service/application/coupon-issue-event-worker/src/test/resources/application.yml
coupon-service/data/jpa/src/main/kotlin/com/hyoseok/coupon/entity/CouponIssuedFailLogEntity.kt
coupon-service/data/jpa/src/main/kotlin/com/hyoseok/coupon/repository/CouponIssuedFailLogJpaReadRepositoryAdapter.kt
coupon-service/data/jpa/src/main/kotlin/com/hyoseok/coupon/repository/CouponIssuedFailLogJpaRepository.kt
coupon-service/data/jpa/src/main/kotlin/com/hyoseok/coupon/repository/CouponIssuedJpaRepositoryAdapter.kt
coupon-service/data/jpa/src/test/kotlin/com/hyoseok/config/JpaRepositoryAdapterTests.kt
coupon-service/data/jpa/src/test/kotlin/com/hyoseok/coupon/repository/CouponIssuedFailLogJpaRepositoryAdapterTests.kt
coupon-service/domain/src/main/kotlin/com/hyoseok/coupon/repository/CouponIssuedFailLogReadRepository.kt

[PR] 이벤트 로그 기능 추가

---

coupon-service/application/coupon-issue-event-worker/src/test/kotlin/com/hyoseok/consumer/KafkaCouponIssuedConsumerTests.kt

[PR] 테스트 결과가 일정하지 않은 테스트 코드 삭제

---

coupon-service/data/redis/src/main/kotlin/com/hyoseok/coupon/repository/CouponRedisRepositoryImpl.kt

[PR] Set 자료구조에 처음 데이터를 넣는 경우, 만료시간 부여

---

coupon-service/data/jpa/src/main/kotlin/com/hyoseok/message/repository/ReceiveMessageFailLogJpaReadRepositoryAdapter.kt
coupon-service/data/jpa/src/main/kotlin/com/hyoseok/message/repository/ReceiveMessageFailLogJpaRepository.kt
coupon-service/data/jpa/src/main/kotlin/com/hyoseok/message/repository/SendMessageFailLogJpaReadRepositoryAdapter.kt
coupon-service/data/jpa/src/main/kotlin/com/hyoseok/message/repository/SendMessageFailLogJpaRepository.kt
coupon-service/data/jpa/src/test/kotlin/com/hyoseok/config/JpaRepositoryAdapterTests.kt
coupon-service/data/jpa/src/test/kotlin/com/hyoseok/message/repository/ReceiveMessageFailLogJpaRepositoryAdapterTests.kt
coupon-service/data/jpa/src/test/kotlin/com/hyoseok/message/repository/SendMessageFailLogRepositoryAdapterTests.kt

[PR] MessageFailLogReadRepository 개발

---

coupon-service/application/coupon-issue-event-worker/src/test/kotlin/com/hyoseok/consumer/KafkaCouponIssuedConsumerTests.kt

[PR] 테스트 코드 주석 해제

---

coupon-service/data/jpa/src/main/kotlin/com/hyoseok/coupon/repository/CouponIssuedJpaRepositoryAdapter.kt
coupon-service/data/jpa/src/main/kotlin/com/hyoseok/coupon/repository/CouponJpaRepositoryAdapter.kt
coupon-service/data/jpa/src/main/kotlin/com/hyoseok/member/repository/MemberJpaRepositoryAdapter.kt
coupon-service/data/jpa/src/main/kotlin/com/hyoseok/message/repository/ReceiveMessageFailLogJpaRepositoryAdapter.kt
coupon-service/data/jpa/src/main/kotlin/com/hyoseok/message/repository/SendMessageFailLogJpaRepositoryAdapter.kt

[PR] also 함수를 사용하여 부수 효과 처리

---

coupon-service/application/coupon-command-api/src/main/kotlin/com/hyoseok/coupon/service/CouponService.kt
coupon-service/application/coupon-command-api/src/main/kotlin/com/hyoseok/member/service/MemberService.kt

[PR] also 함수를 활용한 코드 간소화

---

coupon-service/data/redis/src/main/kotlin/com/hyoseok/coupon/repository/CouponRedisRepositoryImpl.kt
coupon-service/infrastructure/kafka/src/main/kotlin/com/hyoseok/coupon/publisher/KafkaCouponProducer.kt
coupon-service/infrastructure/kafka/src/main/kotlin/com/hyoseok/coupon/publisher/KafkaCouponProducerCallback.kt

[PR] 패키지 경로 변경

---

coupon-service/application/coupon-command-api/src/main/kotlin/com/hyoseok/coupon/service/CouponIssuedService.kt
coupon-service/application/coupon-command-api/src/test/kotlin/com/hyoseok/coupon/service/CouponIssuedServiceTests.kt
coupon-service/data/jpa/src/main/kotlin/com/hyoseok/message/entity/SendMessageLogEntity.kt
coupon-service/data/jpa/src/main/kotlin/com/hyoseok/message/repository/SendMessageLogJpaReadRepositoryAdapter.kt
coupon-service/data/jpa/src/main/kotlin/com/hyoseok/message/repository/SendMessageLogJpaRepository.kt
coupon-service/data/jpa/src/main/kotlin/com/hyoseok/message/repository/SendMessageLogJpaRepositoryAdapter.kt
coupon-service/data/jpa/src/test/kotlin/com/hyoseok/config/JpaRepositoryAdapterTests.kt
coupon-service/data/jpa/src/test/kotlin/com/hyoseok/message/repository/SendMessageLogRepositoryAdapterTests.kt
coupon-service/domain/src/main/kotlin/com/hyoseok/coupon/service/CouponMessageBrokerProducer.kt
coupon-service/domain/src/main/kotlin/com/hyoseok/message/entity/SendMessageLog.kt
coupon-service/domain/src/main/kotlin/com/hyoseok/message/repository/SendMessageLogReadRepository.kt
coupon-service/domain/src/main/kotlin/com/hyoseok/message/repository/SendMessageLogRepository.kt
coupon-service/infrastructure/kafka/src/main/kotlin/com/hyoseok/coupon/publisher/KafkaCouponProducer.kt

[PR] 로그 저장 방식 변경

---

coupon-service/application/coupon-command-api/src/main/kotlin/com/hyoseok/coupon/service/CouponIssuedService.kt
coupon-service/application/coupon-command-api/src/test/kotlin/com/hyoseok/coupon/service/CouponIssuedServiceTests.kt

[PR] CouponIssuedService 리팩토링

---

coupon-service/application/coupon-command-api/src/main/kotlin/com/hyoseok/coupon/service/CouponIssuedService.kt
coupon-service/application/coupon-command-api/src/test/kotlin/com/hyoseok/coupon/service/CouponIssuedServiceTests.kt

[PR] 카프카 메시지 발행전 로그 저장하는 기능 추가

---

coupon-service/application/coupon-command-api/src/main/kotlin/com/hyoseok/coupon/service/CouponIssuedEventHandler.kt
coupon-service/application/coupon-command-api/src/main/kotlin/com/hyoseok/coupon/service/CouponIssuedService.kt
coupon-service/application/coupon-command-api/src/test/kotlin/com/hyoseok/coupon/service/CouponIssuedServiceTests.kt
coupon-service/data/jpa/src/main/kotlin/com/hyoseok/coupon/entity/CouponIssuedLogEntity.kt
coupon-service/data/jpa/src/main/kotlin/com/hyoseok/coupon/repository/CouponIssuedLogJpaReadRepositoryAdapter.kt
coupon-service/data/jpa/src/main/kotlin/com/hyoseok/coupon/repository/CouponIssuedLogJpaRepository.kt
coupon-service/data/jpa/src/main/kotlin/com/hyoseok/coupon/repository/CouponIssuedLogJpaRepositoryAdapter.kt
coupon-service/data/jpa/src/main/kotlin/com/hyoseok/exception/DataJpaMessage.kt
coupon-service/data/jpa/src/test/kotlin/com/hyoseok/config/JpaRepositoryAdapterTests.kt
coupon-service/data/jpa/src/test/kotlin/com/hyoseok/coupon/repository/CouponIssuedLogJpaRepositoryAdapterTests.kt
coupon-service/domain/src/main/kotlin/com/hyoseok/coupon/entity/CouponIssuedLog.kt
coupon-service/domain/src/main/kotlin/com/hyoseok/coupon/repository/CouponIssuedLogReadRepository.kt
coupon-service/domain/src/main/kotlin/com/hyoseok/coupon/repository/CouponIssuedLogRepository.kt
coupon-service/infrastructure/kafka/src/main/kotlin/com/hyoseok/coupon/publisher/KafkaCouponProducerCallback.kt
coupon-service/infrastructure/kafka/src/main/kotlin/com/hyoseok/coupon/publisher/dto/CouponIssuedSendCompletedDto.kt

[PR] CouponIssuedLog 도메인 개발

---

coupon-service/application/batch/build.gradle.kts
coupon-service/application/batch/src/main/kotlin/com/hyoseok/CouponBatchApplication.kt
coupon-service/application/batch/src/main/kotlin/com/hyoseok/config/JobPrefixNames.kt
coupon-service/application/batch/src/main/kotlin/com/hyoseok/job/CouponIssuedEventSendBatchConfig.kt
coupon-service/application/batch/src/main/resources/application.yml
coupon-service/application/batch/src/test/kotlin/com/hyoseok/config/BatchConfig.kt
coupon-service/application/batch/src/test/kotlin/com/hyoseok/integration/CouponIssuedEventSendBatchTests.kt
coupon-service/application/batch/src/test/resources/application.yml
coupon-service/data/jpa/src/main/kotlin/com/hyoseok/coupon/repository/CouponIssuedJpaReadRepositoryAdapter.kt
coupon-service/data/jpa/src/main/kotlin/com/hyoseok/coupon/repository/CouponIssuedJpaRepositoryAdapter.kt
coupon-service/data/jpa/src/main/kotlin/com/hyoseok/coupon/repository/CouponIssuedLogJpaReadRepositoryAdapter.kt
coupon-service/data/jpa/src/main/kotlin/com/hyoseok/coupon/repository/CouponIssuedLogJpaRepositoryAdapter.kt
coupon-service/data/jpa/src/main/kotlin/com/hyoseok/coupon/repository/CouponJpaReadRepositoryAdapter.kt
coupon-service/data/jpa/src/main/kotlin/com/hyoseok/coupon/repository/CouponJpaRepositoryAdapter.kt
coupon-service/data/jpa/src/main/kotlin/com/hyoseok/member/repository/MemberJpaRepositoryAdapter.kt
coupon-service/data/jpa/src/main/kotlin/com/hyoseok/message/repository/ReceiveMessageFailLogJpaReadRepositoryAdapter.kt
coupon-service/data/jpa/src/main/kotlin/com/hyoseok/message/repository/ReceiveMessageFailLogJpaRepositoryAdapter.kt
coupon-service/data/jpa/src/main/kotlin/com/hyoseok/message/repository/SendMessageFailLogJpaReadRepositoryAdapter.kt
coupon-service/data/jpa/src/main/kotlin/com/hyoseok/message/repository/SendMessageFailLogJpaRepositoryAdapter.kt
coupon-service/data/jpa/src/main/kotlin/com/hyoseok/message/repository/SendMessageLogJpaReadRepositoryAdapter.kt
coupon-service/data/jpa/src/main/kotlin/com/hyoseok/message/repository/SendMessageLogJpaRepositoryAdapter.kt
coupon-service/data/jpa/src/test/kotlin/com/hyoseok/coupon/repository/CouponIssuedLogJpaRepositoryAdapterTests.kt
coupon-service/domain/src/main/kotlin/com/hyoseok/coupon/repository/CouponIssuedLogRepository.kt
settings.gradle.kts

[PR] 누락된 이벤트 전송 배치 개발

---

coupon-service/application/coupon-command-api/concurrency-request-test.sh

[PR] 동시성 테스트를 위한 쉘 스크립트 추가

---

.github/workflows/pr-build-and-test.yml
build.gradle.kts

[PR] JDK 17 버전으로 업데이트

---

README.md
build.gradle.kts
coupon-service/application/coupon-command-api/src/main/kotlin/com/hyoseok/coupon/controller/request/CouponCreateRequest.kt
coupon-service/application/coupon-command-api/src/main/kotlin/com/hyoseok/coupon/controller/request/CouponIssuedCreateRequest.kt
coupon-service/application/coupon-command-api/src/main/kotlin/com/hyoseok/member/controller/request/MemberCreateRequest.kt

- `coupon-command-api` 에 Swagger UI 추가 및 Schema 정의

[PR] springdoc-openapi-ui, springdoc-openapi-kotlin 의존성 추가

---

sns-feed-service/application/api/command-server/src/main/kotlin/com/hyoseok/service/dto/FollowCreateResultDto.kt
sns-feed-service/application/api/command-server/src/main/kotlin/com/hyoseok/service/dto/MemberDto.kt
sns-feed-service/application/api/command-server/src/main/kotlin/com/hyoseok/service/follow/FollowService.kt
sns-feed-service/application/api/command-server/src/main/kotlin/com/hyoseok/service/member/MemberReadService.kt
sns-feed-service/application/api/command-server/src/main/kotlin/com/hyoseok/service/member/MemberService.kt
sns-feed-service/application/api/command-server/src/main/kotlin/com/hyoseok/usecase/CreateFollowMemberUsecase.kt
sns-feed-service/application/api/command-server/src/main/kotlin/com/hyoseok/web/FollowController.kt
sns-feed-service/application/api/command-server/src/main/kotlin/com/hyoseok/web/request/FollowCreateRequest.kt
sns-feed-service/domain/src/main/kotlin/com/hyoseok/follow/entity/Follow.kt
sns-feed-service/domain/src/test/kotlin/com/hyoseok/follow/FollowTests.kt

- #138
- Member, Follow 도메인 관심사 분리

[PR] Member, Domain 도메인 비즈니스 리팩토링

---

settings.gradle.kts
sns-feed-service-v2/application/event-worker/src/main/resources/application.yml
sns-feed-service-v2/application/query-api/build.gradle.kts
sns-feed-service-v2/application/query-api/src/main/kotlin/com/hyoseok/SnsFeedQueryApiApplication.kt
sns-feed-service-v2/application/query-api/src/main/kotlin/com/hyoseok/SnsFeedQueryApiGlobalExceptionHandler.kt
sns-feed-service-v2/application/query-api/src/main/kotlin/com/hyoseok/controller/PostController.kt
sns-feed-service-v2/application/query-api/src/main/kotlin/com/hyoseok/usecase/FindPostUsecase.kt
sns-feed-service-v2/application/query-api/src/main/resources/application.yml
sns-feed-service-v2/application/query-api/src/test/resources/application.yml

[PR] application:query-api 모듈 개발

---

coupon-service-v2/domain/redis/build.gradle.kts
coupon-service-v2/domain/redis/src/main/kotlin/com/hyoseok/config/RedisConfig.kt
coupon-service-v2/domain/redis/src/main/kotlin/com/hyoseok/config/RedisMode.kt
coupon-service-v2/domain/redis/src/main/kotlin/com/hyoseok/config/RedisTemplateConfig.kt
coupon-service-v2/domain/redis/src/main/kotlin/com/hyoseok/coupon/dto/CouponIssuedDto.kt
coupon-service-v2/domain/redis/src/main/kotlin/com/hyoseok/coupon/entity/CouponIssued.kt
coupon-service-v2/domain/redis/src/main/kotlin/com/hyoseok/coupon/entity/CouponIssuedStatus.kt
coupon-service-v2/domain/redis/src/main/kotlin/com/hyoseok/coupon/repository/CouponIssuedRedisRepository.kt
coupon-service-v2/domain/redis/src/main/kotlin/com/hyoseok/coupon/repository/CouponIssuedRedisRepositoryImpl.kt
coupon-service-v2/domain/redis/src/main/kotlin/com/hyoseok/coupon/repository/CouponIssuedRedisTransactionRepository.kt
coupon-service-v2/domain/redis/src/main/kotlin/com/hyoseok/coupon/repository/CouponIssuedRedisTransactionRepositoryImpl.kt
coupon-service-v2/domain/redis/src/main/kotlin/com/hyoseok/coupon/service/CouponIssuedService.kt
coupon-service-v2/domain/redis/src/main/resources/config/custom-domain-redis.yml
coupon-service-v2/domain/redis/src/test/kotlin/com/hyoseok/config/RedisEmbbededServerConfig.kt
coupon-service-v2/domain/redis/src/test/kotlin/com/hyoseok/repository/CouponIssuedRedisRepositoryTests.kt
coupon-service-v2/domain/redis/src/test/kotlin/com/hyoseok/repository/CouponIssuedRedisTransactionRepositoryTests.kt
coupon-service-v2/domain/redis/src/test/resources/application.yml
settings.gradle.kts

[PR] domain:redis 모듈 개발

---

coupon-service-v2/domain/rds/src/main/kotlin/com/hyoseok/coupon/constants/CouponErrorMessage.kt
coupon-service-v2/domain/rds/src/main/kotlin/com/hyoseok/coupon/dto/CouponIssuedDto.kt
coupon-service-v2/domain/rds/src/main/kotlin/com/hyoseok/coupon/entity/CouponIssued.kt
coupon-service-v2/domain/rds/src/main/kotlin/com/hyoseok/coupon/repository/CouponIssuedReadRepository.kt
coupon-service-v2/domain/rds/src/main/kotlin/com/hyoseok/coupon/repository/CouponIssuedReadRepositoryImpl.kt
coupon-service-v2/domain/rds/src/main/kotlin/com/hyoseok/coupon/service/CouponIssuedService.kt
coupon-service-v2/domain/rds/src/test/kotlin/com/hyoseok/coupon/repository/CouponIssuedRepositoryTests.kt

- `domain:rds` 모듈 개발
- coupon-issued 관련 기능 개발

[PR] coupon-service-v2 모듈 개발

---

coupon-service-v2/domain/redis/src/main/kotlin/com/hyoseok/coupon/entity/CouponIssuedCache.kt
coupon-service-v2/domain/redis/src/main/kotlin/com/hyoseok/coupon/repository/CouponIssuedRedisRepository.kt
coupon-service-v2/domain/redis/src/main/kotlin/com/hyoseok/coupon/repository/CouponIssuedRedisRepositoryImpl.kt
coupon-service-v2/domain/redis/src/main/kotlin/com/hyoseok/coupon/repository/CouponIssuedRedisTransactionRepositoryImpl.kt
coupon-service-v2/domain/redis/src/main/resources/config/custom-domain-redis.yml
docker/redis/docker-coupon-compose.yml

[PR] coupon-issued-service-v2 모듈 개발

---

sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/wish/dto/WishDto.kt
sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/wish/entity/Wish.kt
sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/wish/repository/WishReadRepository.kt
sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/wish/repository/WishReadRepositoryImpl.kt
sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/wish/repository/WishRepository.kt
sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/wish/service/WishService.kt
sns-feed-service-v2/domain/rds/src/test/kotlin/com/hyoseok/wish/repository/WishRepositoryTests.kt
sns-feed-service-v2/domain/rds/src/test/kotlin/com/hyoseok/wish/service/WishServiceTests.kt
sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/wish/service/WishRedisService.kt
sns-feed-service-v2/domain/redis/src/test/kotlin/com/hyoseok/wish/service/WishRedisServiceTests.kt

- #149
- `domain:rds` 모듈에 wish 도메인 개발
- `domain:redis` 모듈에 wish 도메인 리팩토링

[PR] domain:rds, domain:redis 모듈 개발

---

sns-feed-service-v2/application/api/src/main/kotlin/com/hyoseok/controller/WishController.kt
sns-feed-service-v2/application/api/src/main/kotlin/com/hyoseok/controller/dto/WishCreateRequestDto.kt
sns-feed-service-v2/application/api/src/main/kotlin/com/hyoseok/usecase/CreateWishUsecase.kt
sns-feed-service-v2/application/event-worker/build.gradle.kts
sns-feed-service-v2/application/event-worker/src/main/kotlin/com/hyoseok/config/KafkaConsumerConfig.kt
sns-feed-service-v2/application/event-worker/src/main/kotlin/com/hyoseok/listener/WishKafkaListener.kt
sns-feed-service-v2/application/event-worker/src/main/kotlin/com/hyoseok/listener/WishKafkaListenerErrorHandler.kt
sns-feed-service-v2/application/event-worker/src/main/kotlin/com/hyoseok/listener/dto/WishEventDto.kt
sns-feed-service-v2/application/event-worker/src/main/resources/application.yml
sns-feed-service-v2/application/event-worker/src/test/kotlin/com/hyoseok/listener/FeedKafkaListenerTests.kt
sns-feed-service-v2/application/event-worker/src/test/resources/application.yml
sns-feed-service-v2/application/event-worker/src/test/resources/config/custom-domain-rds.yml
sns-feed-service-v2/application/event-worker/src/test/resources/config/custom-domain-redis.yml
sns-feed-service-v2/client/event-publisher/src/main/kotlin/com/hyoseok/common/AbstractKafkaProducer.kt
sns-feed-service-v2/client/event-publisher/src/main/kotlin/com/hyoseok/wish/dto/WishEventDto.kt
sns-feed-service-v2/client/event-publisher/src/main/kotlin/com/hyoseok/wish/producer/WishKafkaProducer.kt
sns-feed-service-v2/client/event-publisher/src/main/resources/config/custom-client-event-publisher.yml
sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/wish/entity/Wish.kt

- #149
- api, event-worker 모듈 개발

[PR] 좋아요 관련 sns-feed-service-v2 모듈 개발

---

sns-feed-service-v2/application/query-api/src/main/kotlin/com/hyoseok/controller/PostController.kt
sns-feed-service-v2/application/query-api/src/main/kotlin/com/hyoseok/usecase/FindPostTimelineUsecase.kt
sns-feed-service-v2/common/build.gradle.kts
sns-feed-service-v2/common/src/main/kotlin/com/hyoseok/util/PageByPosition.kt
sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/post/repository/PostReadRepository.kt
sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/post/repository/PostReadRepositoryImpl.kt
sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/post/service/PostReadService.kt
sns-feed-service-v2/domain/rds/src/test/kotlin/com/hyoseok/post/repository/PostRepositoryTests.kt
sns-feed-service-v2/domain/redis/build.gradle.kts
sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/common/AbstractRedisRepository.kt
sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/feed/dto/FeedDto.kt
sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/feed/repository/FeedRedisRepository.kt
sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/feed/repository/FeedRedisRepositoryImpl.kt
sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/feed/service/FeedRedisReadService.kt
sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/post/repository/PostRedisRepositoryImpl.kt
sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/post/service/PostRedisReadService.kt
sns-feed-service-v2/domain/redis/src/test/kotlin/com/hyoseok/feed/repository/FeedRedisRepositoryTests.kt

[PR] SNS 타임라인 기능 개발

---

sns-feed-service-v2/application/api/src/main/kotlin/com/hyoseok/usecase/CreatePostUsecase.kt
sns-feed-service-v2/application/api/src/main/kotlin/com/hyoseok/usecase/CreateWishUsecase.kt
sns-feed-service-v2/application/event-worker/src/main/kotlin/com/hyoseok/listener/FeedKafkaListener.kt
sns-feed-service-v2/application/event-worker/src/main/kotlin/com/hyoseok/listener/WishKafkaListener.kt
sns-feed-service-v2/application/event-worker/src/main/kotlin/com/hyoseok/listener/dto/WishEventDto.kt
sns-feed-service-v2/client/event-publisher/src/main/kotlin/com/hyoseok/wish/dto/WishEventDto.kt
sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/wish/dto/WishEventLogDto.kt
sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/wish/entity/WishEventLog.kt
sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/wish/repository/WishEventLogReadRepositoryImpl.kt
sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/wish/repository/WishEventLogRepository.kt
sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/wish/repository/WishReadRepository.kt
sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/wish/repository/WishReadRepositoryImpl.kt
sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/wish/service/WishEventLogService.kt
sns-feed-service-v2/domain/rds/src/test/kotlin/com/hyoseok/wish/repository/WishEventLogRepositoryTests.kt
sns-feed-service-v2/domain/redis/build.gradle.kts
sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/config/FeedRedisConfig.kt
sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/config/PostRedisConfig.kt
sns-feed-service-v2/domain/redis/src/main/resources/config/custom-domain-redis.yml
sns-feed-service-v2/domain/redis/src/test/resources/application.yml

- #157
- Redis Connection Pool 적용
- Redis의 multi 명령어를 사용하면 트랜잭션을 사용할 수 있다.
- 트랜잭션은 매 번 커넥션을 획득하고 반환한다. 이에 따라 비용이 발생한다.
- 위와 같은 이유로 커넥션 풀을 사용하려고 한다. 
- WishEventLog 관련 기능 개발

[PR] sns-feed-service-v2 유지 보수

---

README.md
sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/post/dto/PostCacheDto.kt
sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/post/entity/PostCache.kt
sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/post/repository/PostRedisPipelineRepository.kt
sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/post/repository/PostRedisPipelineRepositoryImpl.kt
sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/post/repository/PostRedisRepository.kt
sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/post/repository/PostRedisRepositoryImpl.kt
sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/post/repository/PostRedisTransactionRepository.kt
sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/post/repository/PostRedisTransactionRepositoryImpl.kt
sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/post/service/PostRedisReadService.kt
sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/post/service/PostRedisService.kt
sns-feed-service-v2/domain/redis/src/test/kotlin/com/hyoseok/post/entity/PostCacheTests.kt
sns-feed-service-v2/domain/redis/src/test/kotlin/com/hyoseok/post/repository/PostRedisPipelineRepositoryTests.kt
sns-feed-service-v2/domain/redis/src/test/kotlin/com/hyoseok/post/repository/PostRedisRepositoryTests.kt

[PR] domain:redis 모듈에서 Post 도메인 Hash 자료구조 적용

---

sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/follow/service/FollowService.kt
sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/member/service/MemberService.kt
sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/post/service/PostService.kt
sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/wish/service/WishEventLogService.kt
sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/wish/service/WishService.kt

[PR] 코드 스타일 변경

---

sns-feed-service-v2/application/query-api/src/main/kotlin/com/hyoseok/controller/PostController.kt
sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/post/repository/PostReadRepository.kt
sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/post/repository/PostReadRepositoryImpl.kt
sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/post/service/PostReadService.kt
sns-feed-service-v2/domain/rds/src/test/kotlin/com/hyoseok/post/repository/PostRepositoryTests.kt

[PR] memberId 기준으로 게시물 페이지네이션 개발

---

sns-feed-service-v2/application/query-api/src/main/kotlin/com/hyoseok/config/resilience4j/ratelimiter/RateLimiterConfig.kt
sns-feed-service-v2/application/query-api/src/main/kotlin/com/hyoseok/config/resilience4j/ratelimiter/property/FindPostsUsecaseProperty.kt
sns-feed-service-v2/application/query-api/src/main/kotlin/com/hyoseok/controller/PostController.kt
sns-feed-service-v2/application/query-api/src/main/kotlin/com/hyoseok/usecase/FindPostsUsecase.kt
sns-feed-service-v2/application/query-api/src/main/resources/application.yml
sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/follow/repository/FollowReadRepository.kt
sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/follow/repository/FollowReadRepositoryImpl.kt
sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/follow/repository/FollowRepository.kt
sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/member/repository/MemberReadRepositoryImpl.kt
sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/post/entity/PostImage.kt
sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/post/repository/PostReadRepositoryImpl.kt
sns-feed-service-v2/domain/rds/src/main/resources/config/custom-domain-rds.yml
sns-feed-service-v2/domain/rds/src/test/kotlin/com/hyoseok/follow/repository/FollowRepositoryTests.kt
sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/post/entity/PostCache.kt
sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/post/repository/PostRedisTransactionRepositoryImpl.kt
sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/post/service/PostRedisReadService.kt
sns-feed-service-v2/domain/redis/src/test/kotlin/com/hyoseok/post/entity/PostCacheTests.kt
sns-feed-service-v2/domain/redis/src/test/kotlin/com/hyoseok/post/repository/PostRedisTransactionRepositoryTests.kt

[PR] Post 리스트 조회 기능 개발

---

sns-feed-service-v2/application/api/src/main/kotlin/com/hyoseok/usecase/CreatePostUsecase.kt
sns-feed-service-v2/application/query-api/src/main/kotlin/com/hyoseok/usecase/FindPostUsecase.kt
sns-feed-service-v2/application/query-api/src/main/kotlin/com/hyoseok/usecase/FindPostsUsecase.kt
sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/post/entity/PostCache.kt
sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/post/repository/PostRedisPipelineRepositoryImpl.kt
sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/post/repository/PostRedisTransactionRepositoryImpl.kt
sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/post/service/PostRedisReadService.kt
sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/post/service/PostRedisService.kt
sns-feed-service-v2/domain/redis/src/test/kotlin/com/hyoseok/post/repository/PostRedisTransactionRepositoryTests.kt

- `hset` -> `set` 자료구조 사용하도록 리팩토링

[PR] Post Redis 도메인 리팩토링

---

sns-feed-service-v2/application/query-api/src/main/kotlin/com/hyoseok/controller/PostController.kt
sns-feed-service-v2/application/query-api/src/main/kotlin/com/hyoseok/usecase/FindPostTimelineUsecase.kt
sns-feed-service-v2/application/query-api/src/main/kotlin/com/hyoseok/usecase/FindPostUsecase.kt
sns-feed-service-v2/application/query-api/src/main/kotlin/com/hyoseok/usecase/FindPostsUsecase.kt
sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/wish/service/WishReadService.kt

[PR] 타임라인 기능에 좋아요 횟수 포함해서 응답하도록 기능 추가

---

sns-feed-service-v2/application/api/src/main/kotlin/com/hyoseok/usecase/CreatePostUsecase.kt
sns-feed-service-v2/application/api/src/main/kotlin/com/hyoseok/usecase/dto/CreatePostUsecaseDto.kt
sns-feed-service-v2/application/api/src/test/kotlin/com/hyoseok/usecase/CreateFollowMemberUsecaseTests.kt
sns-feed-service-v2/application/api/src/test/kotlin/com/hyoseok/usecase/CreatePostUsecaseTests.kt
sns-feed-service-v2/application/api/src/test/kotlin/com/hyoseok/usecase/CreateWishUsecaseTests.kt
sns-feed-service-v2/application/api/src/test/kotlin/com/hyoseok/usecase/UpdateMemberInfluencerUsecaseTests.kt

- `api` 모듈 개발
- 리팩토링
- `usecase` 단위 테스트 코드 작성

[PR] Usecase 단위 테스트 코드 작성

---

sns-feed-service-v2/application/api/src/test/kotlin/com/hyoseok/usecase/CreateFollowMemberUsecaseTests.kt
sns-feed-service-v2/application/api/src/test/kotlin/com/hyoseok/usecase/CreatePostUsecaseTests.kt
sns-feed-service-v2/application/api/src/test/kotlin/com/hyoseok/usecase/CreateWishUsecaseTests.kt
sns-feed-service-v2/application/api/src/test/kotlin/com/hyoseok/usecase/UpdateMemberInfluencerUsecaseTests.kt
sns-feed-service-v2/application/query-api/src/test/kotlin/com/hyoseok/usecase/FindPostUsecaseTests.kt

[PR] query-api 행위 검증 테스트 작성

---

sns-feed-service-v2/application/query-api/src/main/kotlin/com/hyoseok/usecase/FindPostTimelineUsecase.kt
sns-feed-service-v2/common/src/main/kotlin/com/hyoseok/util/PageByPosition.kt
sns-feed-service-v2/common/src/test/kotlin/com/hyoseok/PageRequestByPositionTests.kt
sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/feed/entity/Feed.kt
sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/feed/repository/FeedRedisTransactionRepositoryImpl.kt

[PR] 타임라인 리팩토링

---

sns-feed-service-v2/application/api/src/main/kotlin/com/hyoseok/usecase/CreatePostUsecase.kt
sns-feed-service-v2/application/api/src/test/kotlin/com/hyoseok/usecase/CreateFollowMemberUsecaseTests.kt
sns-feed-service-v2/application/api/src/test/kotlin/com/hyoseok/usecase/CreatePostUsecaseTests.kt
sns-feed-service-v2/application/query-api/src/main/kotlin/com/hyoseok/usecase/FindPostTimelineUsecase.kt
sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/follow/entity/Follow.kt
sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/follow/entity/FollowCount.kt
sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/follow/repository/FollowCountRepository.kt
sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/follow/repository/FollowReadRepository.kt
sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/follow/repository/FollowReadRepositoryImpl.kt
sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/follow/service/FollowReadService.kt
sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/follow/service/FollowService.kt
sns-feed-service-v2/domain/rds/src/test/kotlin/com/hyoseok/follow/entity/FollowCountTests.kt
sns-feed-service-v2/domain/rds/src/test/kotlin/com/hyoseok/follow/repository/FollowRepositoryTests.kt

- `FollowCount` 엔티티 추가
- `Follow` 도메인 관련된 기능 개발

[PR] Follow 도메인 개발

---

.github/workflows/pr-ktlint-check.yml
build.gradle.kts
sns-feed-service-v2/application/query-api/src/main/kotlin/com/hyoseok/usecase/FindPostTimelineUsecase.kt
sns-feed-service-v2/application/query-api/src/main/kotlin/com/hyoseok/usecase/FindPostUsecase.kt
sns-feed-service-v2/application/query-api/src/main/kotlin/com/hyoseok/usecase/FindPostsUsecase.kt
sns-feed-service-v2/application/query-api/src/test/kotlin/com/hyoseok/usecase/FindPostUsecaseTests.kt
sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/follow/entity/Follow.kt
sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/post/entity/Post.kt
sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/post/service/PostReadService.kt
sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/wish/entity/Wish.kt
sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/wish/service/WishReadService.kt
sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/feed/service/FeedRedisReadService.kt
sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/wish/service/WishRedisReadService.kt
sns-feed-service-v2/domain/redis/src/test/kotlin/com/hyoseok/wish/service/WishRedisReadServiceTests.kt

[PR] query-api 모듈 리팩토링

---

sns-feed-service-v2/application/query-api/src/main/kotlin/com/hyoseok/usecase/FindPostsTimelineUsecase.kt
sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/follow/entity/Follow.kt
sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/follow/entity/FollowCount.kt
sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/follow/repository/FollowReadRepository.kt
sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/follow/repository/FollowReadRepositoryImpl.kt
sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/follow/service/FollowReadService.kt
sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/member/service/MemberReadService.kt
sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/post/repository/PostReadRepository.kt
sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/post/repository/PostReadRepositoryImpl.kt
sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/post/service/PostReadService.kt
sns-feed-service-v2/domain/rds/src/test/kotlin/com/hyoseok/follow/repository/FollowRepositoryTests.kt
sns-feed-service-v2/domain/rds/src/test/kotlin/com/hyoseok/post/repository/PostRepositoryTests.kt
sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/feed/entity/Feed.kt
sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/post/entity/PostCache.kt
sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/post/repository/PostRedisRepository.kt
sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/post/repository/PostRedisRepositoryImpl.kt
sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/post/repository/PostRedisTransactionRepositoryImpl.kt
sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/post/service/PostRedisReadService.kt
sns-feed-service-v2/domain/redis/src/test/kotlin/com/hyoseok/post/repository/PostRedisTransactionRepositoryTests.kt

- `Feed` 캐시에 있는 `Post` 만 볼 수 있도록 리팩토링

[PR] FindPostTimelineUsecase 리팩토링

---

sns-feed-service-v2/application/query-api/src/main/kotlin/com/hyoseok/usecase/FindPostsUsecase.kt
sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/post/service/PostRedisReadService.kt

- 캐시 응답
- 캐시 없을시, DB 조회 및 캐시 갱신 처리

[PR] FindPostsUsecase 리팩토링

---

build.gradle.kts
sns-feed-service-v2/application/batch/build.gradle.kts

- `testImplementation("org.springframework.batch:spring-batch-test")` 를 루트 `build.gradle.kts` 에 위치 해두면, 테스트 코드가 에러남

[PR] build.gradle.kts 수정

---

.github/workflows/pr-build-and-test.yml
docker/redis/docker-compose.yml
sns-feed-service-v2/application/api/src/main/resources/application.yml
sns-feed-service-v2/application/batch/build.gradle.kts
sns-feed-service-v2/application/batch/src/main/kotlin/com/hyoseok/job/WishCountToPostBatchJobConfig.kt
sns-feed-service-v2/application/batch/src/main/resources/application.yml
sns-feed-service-v2/application/batch/src/test/kotlin/com/hyoseok/config/BatchConfig.kt
sns-feed-service-v2/application/batch/src/test/kotlin/com/hyoseok/job/WishCountToPostBatchJobConfigTests.kt
sns-feed-service-v2/application/batch/src/test/resources/application.yml
sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/wish/repository/WishRedisRepository.kt
sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/wish/repository/WishRedisRepositoryImpl.kt
sns-feed-service-v2/domain/redis/src/test/kotlin/com/hyoseok/config/RedisEmbbededServerConfig.kt
sns-feed-service-v2/domain/redis/src/test/kotlin/com/hyoseok/wish/repository/WishRedisRepositoryTests.kt

- `application:batch`
- `domin:redis`

[PR] Wish 캐시를 Post 엔티티 wishCount 프로퍼티에 일괄 반영하는 Batch Job 개발

---

sns-feed-service-v2/application/batch/src/main/kotlin/com/hyoseok/job/PostToPostCacheBatchJobConfig.kt
sns-feed-service-v2/application/batch/src/main/kotlin/com/hyoseok/job/WishCountToPostBatchJobConfig.kt
sns-feed-service-v2/application/batch/src/test/kotlin/com/hyoseok/job/PostToPostCacheBatchJobConfigTests.kt
sns-feed-service-v2/application/batch/src/test/kotlin/com/hyoseok/job/WishCountToPostBatchJobConfigTests.kt
sns-feed-service-v2/application/batch/src/test/resources/application.yml
sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/post/repository/PostReadRepositoryImpl.kt
sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/post/service/PostReadService.kt
sns-feed-service-v2/domain/redis/src/test/kotlin/com/hyoseok/wish/repository/WishRedisRepositoryTests.kt

- `application:batch` 개발
- `domain:rds` 개발

[PR] Post 엔티티에서 PostCache 이관 BatchJob 개발

---

sns-feed-service-v2/application/batch/src/main/kotlin/com/hyoseok/job/PostToPostCacheBatchJobConfig.kt
sns-feed-service-v2/application/query-api/src/main/kotlin/com/hyoseok/usecase/FindPostsTimelineUsecase.kt
sns-feed-service-v2/application/query-api/src/main/kotlin/com/hyoseok/usecase/FindPostsUsecase.kt
sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/post/service/PostReadService.kt
sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/feed/service/FeedRedisReadService.kt
sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/post/entity/PostCache.kt
sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/post/repository/PostRedisRepository.kt
sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/post/repository/PostRedisRepositoryImpl.kt
sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/post/service/PostRedisReadService.kt
sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/post/service/PostRedisService.kt

- `application:batch` 모듈 수정
- `application:query-api` 모듈 기능 추가 및 리팩토링
- `domain:redis` 모듈 리팩토링

[PR] Post Redis 도메인 리팩토링 및 Batch 수정

---

sns-feed-service-v2/application/query-api/src/main/kotlin/com/hyoseok/usecase/FindPostsTimelineUsecase.kt
sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/feed/dto/FeedCacheDto.kt
sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/feed/entity/FeedCache.kt
sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/feed/repository/FeedRedisTransactionRepositoryImpl.kt
sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/feed/service/FeedRedisReadService.kt
sns-feed-service-v2/domain/redis/src/test/kotlin/com/hyoseok/feed/repository/FeedRedisRepositoryTests.kt

- #187
- `Feed` 캐시 만료 시간 삭제
- `Feed` -> `FeedCache` 로 이름 변경

[PR] Feed 캐시 만료 시간 삭제 및 FeedCache 이름 변경

---

sns-feed-service-v2/application/query-api/src/main/kotlin/com/hyoseok/usecase/FindPostsTimelineUsecase.kt

- #189
- DB 에서 인플루언서 followeeId 리스트 조회 및 Post 조회 로직 제거

[PR] DB 조회 기능 삭제

---

sns-feed-service-v2/domain/rds/src/main/kotlin/com/hyoseok/follow/entity/FollowCount.kt

- #189
- `INFLUENCER_MIN_LIMIT_COUNT` 값 `1,000,000` 으로 수정

[PR] INFLUENCER_MIN_LIMIT_COUNT 값 1,000,000 으로 수정

---

sns-feed-service-v2/domain/redis/src/main/kotlin/com/hyoseok/post/service/PostRedisReadService.kt

- #195
- `Post` 캐시 리스트 조회 방식을 `mget` 명령어로 조회

[PR] mget 메서드로 변경
